// A compact, hand-rolled emoji set for the chat composer's quick-insert picker.
// Deliberately NOT the curated reaction glyphs (those are skinnable / theme-
// overridden); these are raw Unicode inserted straight into the message text, so
// they render the same for everyone and survive a theme. `k` is a space-joined
// keyword string the search box matches against (substring, case-insensitive).
export interface EmojiItem {
  e: string
  k: string
}
export interface EmojiCategory {
  key: string
  icon: string // PrimeVue icon class for the tab
  items: EmojiItem[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: 'smileys',
    icon: 'pi pi-face-smile',
    items: [
      { e: '😀', k: 'grin smile happy' },
      { e: '😃', k: 'smile happy joy' },
      { e: '😄', k: 'smile happy laugh' },
      { e: '😁', k: 'grin beam' },
      { e: '😆', k: 'laugh squint' },
      { e: '😅', k: 'sweat laugh nervous' },
      { e: '🤣', k: 'rofl rolling laugh' },
      { e: '😂', k: 'joy tears laugh cry' },
      { e: '🙂', k: 'slight smile' },
      { e: '🙃', k: 'upside down silly' },
      { e: '😉', k: 'wink' },
      { e: '😊', k: 'blush smile happy' },
      { e: '😇', k: 'innocent halo angel' },
      { e: '🥰', k: 'love hearts adore' },
      { e: '😍', k: 'heart eyes love' },
      { e: '🤩', k: 'star struck wow' },
      { e: '😘', k: 'kiss blow' },
      { e: '😗', k: 'kiss' },
      { e: '😋', k: 'yum tongue tasty' },
      { e: '😛', k: 'tongue cheeky' },
      { e: '😜', k: 'wink tongue silly' },
      { e: '🤪', k: 'zany crazy goofy' },
      { e: '😝', k: 'tongue squint' },
      { e: '🤑', k: 'money mouth rich' },
      { e: '🤗', k: 'hug' },
      { e: '🤭', k: 'giggle oops hand' },
      { e: '🤫', k: 'shush quiet' },
      { e: '🤔', k: 'thinking hmm' },
      { e: '🤐', k: 'zipper mouth quiet' },
      { e: '🤨', k: 'raised eyebrow skeptic' },
      { e: '😐', k: 'neutral meh' },
      { e: '😑', k: 'expressionless' },
      { e: '😶', k: 'no mouth speechless' },
      { e: '😏', k: 'smirk sly' },
      { e: '😒', k: 'unamused meh' },
      { e: '🙄', k: 'eye roll' },
      { e: '😬', k: 'grimace awkward' },
      { e: '😮‍💨', k: 'relieved sigh exhale' },
      { e: '🤥', k: 'lying nose' },
      { e: '😌', k: 'relieved calm' },
      { e: '😔', k: 'pensive sad' },
      { e: '😪', k: 'sleepy tired' },
      { e: '🤤', k: 'drool' },
      { e: '😴', k: 'sleep zzz' },
      { e: '😷', k: 'mask sick' },
      { e: '🤒', k: 'thermometer sick' },
      { e: '🤕', k: 'bandage hurt' },
      { e: '🤧', k: 'sneeze tissue' },
      { e: '🥵', k: 'hot heat sweat' },
      { e: '🥶', k: 'cold freezing' },
      { e: '🥴', k: 'woozy dizzy drunk' },
      { e: '😵', k: 'dizzy knockout' },
      { e: '🤯', k: 'mind blown explode' },
      { e: '🤠', k: 'cowboy' },
      { e: '🥳', k: 'party celebrate hat' },
      { e: '😎', k: 'cool sunglasses' },
      { e: '🤓', k: 'nerd glasses' },
      { e: '🧐', k: 'monocle inspect' },
      { e: '😕', k: 'confused' },
      { e: '😟', k: 'worried' },
      { e: '🙁', k: 'frown sad' },
      { e: '😮', k: 'open mouth wow surprise' },
      { e: '😯', k: 'hushed surprise' },
      { e: '😲', k: 'astonished shocked' },
      { e: '😳', k: 'flushed embarrassed' },
      { e: '🥺', k: 'pleading puppy beg' },
      { e: '😦', k: 'frown open' },
      { e: '😧', k: 'anguished' },
      { e: '😨', k: 'fearful scared' },
      { e: '😰', k: 'anxious sweat' },
      { e: '😥', k: 'sad relieved' },
      { e: '😢', k: 'cry sad tear' },
      { e: '😭', k: 'sob cry bawl' },
      { e: '😱', k: 'scream shock fear' },
      { e: '😖', k: 'confounded' },
      { e: '😣', k: 'persevere struggle' },
      { e: '😞', k: 'disappointed sad' },
      { e: '😓', k: 'sweat downcast' },
      { e: '😩', k: 'weary tired' },
      { e: '😫', k: 'tired fed up' },
      { e: '🥱', k: 'yawn bored' },
      { e: '😤', k: 'triumph steam huff' },
      { e: '😡', k: 'rage angry mad' },
      { e: '😠', k: 'angry mad' },
      { e: '🤬', k: 'swear curse angry' },
      { e: '😈', k: 'devil smiling imp' },
      { e: '👿', k: 'devil angry imp' },
      { e: '💀', k: 'skull dead' },
      { e: '💩', k: 'poop' },
      { e: '🤡', k: 'clown' },
      { e: '👻', k: 'ghost boo' },
      { e: '👽', k: 'alien' },
      { e: '🤖', k: 'robot bot' },
    ],
  },
  {
    key: 'people',
    icon: 'pi pi-user',
    items: [
      { e: '👋', k: 'wave hi bye hello' },
      { e: '🤚', k: 'raised back hand' },
      { e: '✋', k: 'hand stop high five' },
      { e: '🖐️', k: 'hand fingers' },
      { e: '👌', k: 'ok perfect' },
      { e: '🤌', k: 'pinched italian' },
      { e: '🤏', k: 'pinch small' },
      { e: '✌️', k: 'victory peace' },
      { e: '🤞', k: 'fingers crossed luck' },
      { e: '🤟', k: 'love you' },
      { e: '🤘', k: 'rock horns' },
      { e: '🤙', k: 'call me shaka' },
      { e: '👈', k: 'point left' },
      { e: '👉', k: 'point right' },
      { e: '👆', k: 'point up' },
      { e: '👇', k: 'point down' },
      { e: '☝️', k: 'point up one' },
      { e: '👍', k: 'thumbs up like yes' },
      { e: '👎', k: 'thumbs down dislike no' },
      { e: '✊', k: 'fist raised' },
      { e: '👊', k: 'fist punch bump' },
      { e: '🤛', k: 'fist left' },
      { e: '🤜', k: 'fist right' },
      { e: '👏', k: 'clap applause' },
      { e: '🙌', k: 'raised hands celebrate praise' },
      { e: '👐', k: 'open hands' },
      { e: '🤲', k: 'palms together' },
      { e: '🤝', k: 'handshake deal' },
      { e: '🙏', k: 'pray thanks please' },
      { e: '✍️', k: 'writing hand' },
      { e: '💪', k: 'muscle strong flex' },
      { e: '🦵', k: 'leg' },
      { e: '🦶', k: 'foot' },
      { e: '👀', k: 'eyes look' },
      { e: '👁️', k: 'eye' },
      { e: '👅', k: 'tongue' },
      { e: '👄', k: 'lips mouth' },
      { e: '🧠', k: 'brain smart' },
      { e: '🫀', k: 'heart organ' },
      { e: '👶', k: 'baby' },
      { e: '🧒', k: 'child kid' },
      { e: '👦', k: 'boy' },
      { e: '👧', k: 'girl' },
      { e: '🧑', k: 'person adult' },
      { e: '👨', k: 'man' },
      { e: '👩', k: 'woman' },
      { e: '🧔', k: 'beard person' },
      { e: '👴', k: 'old man grandpa' },
      { e: '👵', k: 'old woman grandma' },
      { e: '🙇', k: 'bow sorry' },
      { e: '🤦', k: 'facepalm' },
      { e: '🤷', k: 'shrug dunno' },
      { e: '👮', k: 'police cop' },
      { e: '🕵️', k: 'detective spy' },
      { e: '💂', k: 'guard' },
      { e: '👷', k: 'construction worker' },
      { e: '🤴', k: 'prince' },
      { e: '👸', k: 'princess' },
      { e: '🦸', k: 'superhero' },
      { e: '🦹', k: 'supervillain' },
      { e: '🎅', k: 'santa christmas' },
      { e: '🤶', k: 'mrs claus' },
      { e: '💃', k: 'dancer dance' },
      { e: '🕺', k: 'man dancing' },
      { e: '👯', k: 'bunny ears dancing' },
      { e: '🚶', k: 'walk' },
      { e: '🏃', k: 'run' },
      { e: '🧗', k: 'climb' },
      { e: '🏆', k: 'trophy win' },
    ],
  },
  {
    key: 'animals',
    icon: 'pi pi-github',
    items: [
      { e: '🐶', k: 'dog puppy' },
      { e: '🐱', k: 'cat kitten' },
      { e: '🐭', k: 'mouse' },
      { e: '🐹', k: 'hamster' },
      { e: '🐰', k: 'rabbit bunny' },
      { e: '🦊', k: 'fox' },
      { e: '🐻', k: 'bear' },
      { e: '🐼', k: 'panda' },
      { e: '🐨', k: 'koala' },
      { e: '🐯', k: 'tiger' },
      { e: '🦁', k: 'lion' },
      { e: '🐮', k: 'cow' },
      { e: '🐷', k: 'pig' },
      { e: '🐸', k: 'frog' },
      { e: '🐵', k: 'monkey' },
      { e: '🙈', k: 'see no evil monkey' },
      { e: '🐔', k: 'chicken' },
      { e: '🐧', k: 'penguin' },
      { e: '🐦', k: 'bird' },
      { e: '🦅', k: 'eagle' },
      { e: '🦆', k: 'duck' },
      { e: '🦉', k: 'owl' },
      { e: '🐺', k: 'wolf' },
      { e: '🐗', k: 'boar' },
      { e: '🐴', k: 'horse' },
      { e: '🦄', k: 'unicorn' },
      { e: '🐝', k: 'bee' },
      { e: '🐛', k: 'bug caterpillar' },
      { e: '🦋', k: 'butterfly' },
      { e: '🐌', k: 'snail' },
      { e: '🐞', k: 'ladybug' },
      { e: '🐢', k: 'turtle' },
      { e: '🐍', k: 'snake' },
      { e: '🦖', k: 'dino t-rex' },
      { e: '🐙', k: 'octopus' },
      { e: '🦑', k: 'squid' },
      { e: '🦐', k: 'shrimp' },
      { e: '🦀', k: 'crab' },
      { e: '🐠', k: 'fish tropical' },
      { e: '🐟', k: 'fish' },
      { e: '🐬', k: 'dolphin' },
      { e: '🐳', k: 'whale' },
      { e: '🦈', k: 'shark' },
      { e: '🐊', k: 'crocodile' },
      { e: '🐅', k: 'tiger big' },
      { e: '🦓', k: 'zebra' },
      { e: '🦍', k: 'gorilla' },
      { e: '🐘', k: 'elephant' },
      { e: '🐪', k: 'camel' },
      { e: '🦒', k: 'giraffe' },
      { e: '🐄', k: 'cow' },
      { e: '🐑', k: 'sheep' },
      { e: '🐐', k: 'goat' },
      { e: '🌵', k: 'cactus plant' },
      { e: '🌲', k: 'tree evergreen' },
      { e: '🌳', k: 'tree' },
      { e: '🌴', k: 'palm tree' },
      { e: '🌱', k: 'seedling sprout' },
      { e: '🌿', k: 'herb leaf' },
      { e: '🍀', k: 'clover luck' },
      { e: '🌸', k: 'blossom flower' },
      { e: '🌹', k: 'rose flower' },
      { e: '🌻', k: 'sunflower' },
      { e: '🌼', k: 'flower daisy' },
      { e: '🌷', k: 'tulip' },
      { e: '🍄', k: 'mushroom' },
      { e: '🌍', k: 'earth globe world' },
      { e: '🌙', k: 'moon crescent' },
      { e: '⭐', k: 'star' },
      { e: '🌟', k: 'glowing star sparkle' },
      { e: '⚡', k: 'lightning bolt zap' },
      { e: '🔥', k: 'fire lit hot' },
      { e: '🌈', k: 'rainbow' },
      { e: '☀️', k: 'sun sunny' },
      { e: '⛅', k: 'cloud sun' },
      { e: '❄️', k: 'snowflake cold' },
      { e: '💧', k: 'droplet water' },
      { e: '🌊', k: 'wave ocean' },
    ],
  },
  {
    key: 'food',
    icon: 'pi pi-apple',
    items: [
      { e: '🍏', k: 'green apple' },
      { e: '🍎', k: 'apple red' },
      { e: '🍐', k: 'pear' },
      { e: '🍊', k: 'orange tangerine' },
      { e: '🍋', k: 'lemon' },
      { e: '🍌', k: 'banana' },
      { e: '🍉', k: 'watermelon' },
      { e: '🍇', k: 'grapes' },
      { e: '🍓', k: 'strawberry' },
      { e: '🫐', k: 'blueberries' },
      { e: '🍒', k: 'cherries' },
      { e: '🍑', k: 'peach' },
      { e: '🥭', k: 'mango' },
      { e: '🍍', k: 'pineapple' },
      { e: '🥥', k: 'coconut' },
      { e: '🥝', k: 'kiwi' },
      { e: '🍅', k: 'tomato' },
      { e: '🥑', k: 'avocado' },
      { e: '🍆', k: 'eggplant aubergine' },
      { e: '🥔', k: 'potato' },
      { e: '🥕', k: 'carrot' },
      { e: '🌽', k: 'corn' },
      { e: '🌶️', k: 'chili pepper spicy' },
      { e: '🥦', k: 'broccoli' },
      { e: '🧄', k: 'garlic' },
      { e: '🧅', k: 'onion' },
      { e: '🍞', k: 'bread' },
      { e: '🥐', k: 'croissant' },
      { e: '🥨', k: 'pretzel' },
      { e: '🧀', k: 'cheese' },
      { e: '🥚', k: 'egg' },
      { e: '🍳', k: 'fried egg cooking' },
      { e: '🥞', k: 'pancakes' },
      { e: '🥓', k: 'bacon' },
      { e: '🍔', k: 'burger hamburger' },
      { e: '🍟', k: 'fries chips' },
      { e: '🍕', k: 'pizza' },
      { e: '🌭', k: 'hot dog' },
      { e: '🥪', k: 'sandwich' },
      { e: '🌮', k: 'taco' },
      { e: '🌯', k: 'burrito' },
      { e: '🥙', k: 'kebab pita' },
      { e: '🍜', k: 'ramen noodles' },
      { e: '🍝', k: 'pasta spaghetti' },
      { e: '🍣', k: 'sushi' },
      { e: '🍱', k: 'bento' },
      { e: '🍚', k: 'rice' },
      { e: '🍙', k: 'rice ball' },
      { e: '🍦', k: 'ice cream soft' },
      { e: '🍰', k: 'cake slice' },
      { e: '🎂', k: 'birthday cake' },
      { e: '🧁', k: 'cupcake' },
      { e: '🍩', k: 'donut' },
      { e: '🍪', k: 'cookie' },
      { e: '🍫', k: 'chocolate' },
      { e: '🍬', k: 'candy sweet' },
      { e: '🍭', k: 'lollipop' },
      { e: '🍿', k: 'popcorn' },
      { e: '☕', k: 'coffee tea hot' },
      { e: '🍵', k: 'tea green' },
      { e: '🥤', k: 'cup straw soda' },
      { e: '🍺', k: 'beer' },
      { e: '🍻', k: 'beers cheers' },
      { e: '🍷', k: 'wine' },
      { e: '🥂', k: 'champagne cheers toast' },
      { e: '🍸', k: 'cocktail martini' },
      { e: '🍾', k: 'bottle pop champagne' },
    ],
  },
  {
    key: 'activities',
    icon: 'pi pi-star',
    items: [
      { e: '⚽', k: 'soccer football' },
      { e: '🏀', k: 'basketball' },
      { e: '🏈', k: 'american football' },
      { e: '⚾', k: 'baseball' },
      { e: '🥎', k: 'softball' },
      { e: '🎾', k: 'tennis' },
      { e: '🏐', k: 'volleyball' },
      { e: '🏉', k: 'rugby' },
      { e: '🥏', k: 'frisbee disc' },
      { e: '🎱', k: 'pool 8 ball' },
      { e: '🏓', k: 'ping pong table tennis' },
      { e: '🏸', k: 'badminton' },
      { e: '🥅', k: 'goal net' },
      { e: '⛳', k: 'golf flag' },
      { e: '🏒', k: 'hockey' },
      { e: '🏑', k: 'field hockey' },
      { e: '🥍', k: 'lacrosse' },
      { e: '🏏', k: 'cricket' },
      { e: '🥊', k: 'boxing glove' },
      { e: '🥋', k: 'martial arts' },
      { e: '🎽', k: 'running shirt' },
      { e: '⛸️', k: 'ice skate' },
      { e: '🥌', k: 'curling' },
      { e: '🛷', k: 'sled' },
      { e: '🎿', k: 'ski' },
      { e: '🏂', k: 'snowboard' },
      { e: '🏄', k: 'surf' },
      { e: '🏊', k: 'swim' },
      { e: '🚴', k: 'cycling bike' },
      { e: '🏋️', k: 'weight lifting gym' },
      { e: '🤸', k: 'cartwheel gymnast' },
      { e: '🤺', k: 'fencing' },
      { e: '🤼', k: 'wrestling' },
      { e: '🏇', k: 'horse racing' },
      { e: '🥇', k: 'gold medal first' },
      { e: '🥈', k: 'silver medal second' },
      { e: '🥉', k: 'bronze medal third' },
      { e: '🏅', k: 'medal' },
      { e: '🎖️', k: 'military medal' },
      { e: '🎫', k: 'ticket' },
      { e: '🎟️', k: 'admission tickets' },
      { e: '🎪', k: 'circus tent' },
      { e: '🎭', k: 'theater masks drama' },
      { e: '🎨', k: 'art palette paint' },
      { e: '🎬', k: 'clapper film movie' },
      { e: '🎤', k: 'microphone sing' },
      { e: '🎧', k: 'headphones' },
      { e: '🎼', k: 'music score' },
      { e: '🎹', k: 'piano keyboard' },
      { e: '🥁', k: 'drum' },
      { e: '🎸', k: 'guitar' },
      { e: '🎺', k: 'trumpet' },
      { e: '🎻', k: 'violin' },
      { e: '🎲', k: 'dice game' },
      { e: '♟️', k: 'chess pawn' },
      { e: '🎯', k: 'dart target bullseye' },
      { e: '🎳', k: 'bowling' },
      { e: '🎮', k: 'video game controller' },
      { e: '🕹️', k: 'joystick' },
      { e: '🎰', k: 'slot machine' },
      { e: '🧩', k: 'puzzle piece' },
      { e: '🎉', k: 'party tada celebrate' },
      { e: '🎊', k: 'confetti ball' },
      { e: '🎈', k: 'balloon' },
      { e: '🎁', k: 'gift present' },
    ],
  },
  {
    key: 'travel',
    icon: 'pi pi-car',
    items: [
      { e: '🚗', k: 'car' },
      { e: '🚕', k: 'taxi' },
      { e: '🚙', k: 'suv car' },
      { e: '🚌', k: 'bus' },
      { e: '🏎️', k: 'race car' },
      { e: '🚓', k: 'police car' },
      { e: '🚑', k: 'ambulance' },
      { e: '🚒', k: 'fire truck' },
      { e: '🚜', k: 'tractor' },
      { e: '🛵', k: 'scooter moped' },
      { e: '🏍️', k: 'motorcycle' },
      { e: '🚲', k: 'bike bicycle' },
      { e: '✈️', k: 'plane flight' },
      { e: '🚀', k: 'rocket launch' },
      { e: '🛸', k: 'ufo' },
      { e: '🚁', k: 'helicopter' },
      { e: '⛵', k: 'sailboat' },
      { e: '🚤', k: 'speedboat' },
      { e: '🛳️', k: 'cruise ship' },
      { e: '🚢', k: 'ship' },
      { e: '🚂', k: 'train steam' },
      { e: '🚆', k: 'train' },
      { e: '🚇', k: 'metro subway' },
      { e: '🚦', k: 'traffic light' },
      { e: '🗺️', k: 'map' },
      { e: '🗿', k: 'moai statue' },
      { e: '🗽', k: 'statue liberty' },
      { e: '🗼', k: 'tokyo tower' },
      { e: '🏰', k: 'castle' },
      { e: '🏯', k: 'japanese castle' },
      { e: '🏟️', k: 'stadium' },
      { e: '🎡', k: 'ferris wheel' },
      { e: '🎢', k: 'roller coaster' },
      { e: '🏖️', k: 'beach' },
      { e: '🏝️', k: 'island' },
      { e: '⛰️', k: 'mountain' },
      { e: '🌋', k: 'volcano' },
      { e: '🏕️', k: 'camping tent' },
      { e: '🏠', k: 'house home' },
      { e: '🏢', k: 'office building' },
      { e: '🏥', k: 'hospital' },
      { e: '🏦', k: 'bank' },
      { e: '🏨', k: 'hotel' },
      { e: '🏫', k: 'school' },
      { e: '⛩️', k: 'shrine' },
      { e: '🕌', k: 'mosque' },
      { e: '⛪', k: 'church' },
      { e: '🌃', k: 'night city stars' },
      { e: '🌉', k: 'bridge night' },
      { e: '🎇', k: 'sparkler firework' },
      { e: '🎆', k: 'fireworks' },
    ],
  },
  {
    key: 'objects',
    icon: 'pi pi-mobile',
    items: [
      { e: '⌚', k: 'watch time' },
      { e: '📱', k: 'phone mobile' },
      { e: '💻', k: 'laptop computer' },
      { e: '🖥️', k: 'desktop computer' },
      { e: '⌨️', k: 'keyboard' },
      { e: '🖨️', k: 'printer' },
      { e: '🖱️', k: 'mouse computer' },
      { e: '💾', k: 'floppy save disk' },
      { e: '💿', k: 'cd disc' },
      { e: '📷', k: 'camera photo' },
      { e: '📸', k: 'camera flash' },
      { e: '🎥', k: 'movie camera' },
      { e: '📺', k: 'tv television' },
      { e: '📻', k: 'radio' },
      { e: '☎️', k: 'phone telephone' },
      { e: '🔋', k: 'battery' },
      { e: '🔌', k: 'plug power' },
      { e: '💡', k: 'bulb idea light' },
      { e: '🔦', k: 'flashlight torch' },
      { e: '🕯️', k: 'candle' },
      { e: '💰', k: 'money bag' },
      { e: '💵', k: 'dollar cash money' },
      { e: '💳', k: 'credit card' },
      { e: '💎', k: 'diamond gem' },
      { e: '⚖️', k: 'scales justice balance' },
      { e: '🔧', k: 'wrench tool fix' },
      { e: '🔨', k: 'hammer' },
      { e: '🛠️', k: 'tools' },
      { e: '⚙️', k: 'gear settings cog' },
      { e: '🔩', k: 'nut bolt' },
      { e: '🧲', k: 'magnet' },
      { e: '🔫', k: 'water gun' },
      { e: '💣', k: 'bomb' },
      { e: '🔪', k: 'knife' },
      { e: '🛡️', k: 'shield' },
      { e: '🚬', k: 'cigarette smoke' },
      { e: '🔒', k: 'lock secure' },
      { e: '🔑', k: 'key' },
      { e: '🗝️', k: 'old key' },
      { e: '🚪', k: 'door' },
      { e: '🛋️', k: 'couch sofa' },
      { e: '🛏️', k: 'bed' },
      { e: '🚽', k: 'toilet' },
      { e: '🚿', k: 'shower' },
      { e: '🛒', k: 'shopping cart' },
      { e: '🎀', k: 'ribbon bow' },
      { e: '📦', k: 'package box' },
      { e: '📫', k: 'mailbox' },
      { e: '✉️', k: 'envelope mail' },
      { e: '📝', k: 'memo note write' },
      { e: '📚', k: 'books' },
      { e: '📖', k: 'book open read' },
      { e: '📅', k: 'calendar date' },
      { e: '📌', k: 'pin pushpin' },
      { e: '📎', k: 'paperclip' },
      { e: '✂️', k: 'scissors cut' },
      { e: '🖊️', k: 'pen' },
      { e: '✏️', k: 'pencil' },
      { e: '🔍', k: 'search magnify' },
      { e: '🔬', k: 'microscope science' },
      { e: '🔭', k: 'telescope' },
      { e: '💊', k: 'pill medicine' },
      { e: '💉', k: 'syringe shot' },
      { e: '🩹', k: 'bandage plaster' },
    ],
  },
  {
    key: 'symbols',
    icon: 'pi pi-heart',
    items: [
      { e: '❤️', k: 'red heart love' },
      { e: '🧡', k: 'orange heart' },
      { e: '💛', k: 'yellow heart' },
      { e: '💚', k: 'green heart' },
      { e: '💙', k: 'blue heart' },
      { e: '💜', k: 'purple heart' },
      { e: '🖤', k: 'black heart' },
      { e: '🤍', k: 'white heart' },
      { e: '🤎', k: 'brown heart' },
      { e: '💔', k: 'broken heart' },
      { e: '❣️', k: 'heart exclamation' },
      { e: '💕', k: 'two hearts' },
      { e: '💞', k: 'revolving hearts' },
      { e: '💓', k: 'beating heart' },
      { e: '💗', k: 'growing heart' },
      { e: '💖', k: 'sparkling heart' },
      { e: '💘', k: 'heart arrow cupid' },
      { e: '💝', k: 'heart gift' },
      { e: '💯', k: 'hundred 100 perfect' },
      { e: '💢', k: 'anger symbol' },
      { e: '💥', k: 'collision boom' },
      { e: '💫', k: 'dizzy stars' },
      { e: '💦', k: 'sweat drops splash' },
      { e: '💨', k: 'dash wind fast' },
      { e: '🕳️', k: 'hole' },
      { e: '💬', k: 'speech bubble chat' },
      { e: '💭', k: 'thought bubble' },
      { e: '🗯️', k: 'anger speech' },
      { e: '♠️', k: 'spades' },
      { e: '♥️', k: 'hearts card' },
      { e: '♦️', k: 'diamonds card' },
      { e: '♣️', k: 'clubs card' },
      { e: '✅', k: 'check tick done yes' },
      { e: '❌', k: 'cross x no wrong' },
      { e: '❎', k: 'cross button' },
      { e: '➕', k: 'plus add' },
      { e: '➖', k: 'minus subtract' },
      { e: '➗', k: 'divide' },
      { e: '✖️', k: 'multiply times' },
      { e: '❓', k: 'question mark' },
      { e: '❗', k: 'exclamation' },
      { e: '⚠️', k: 'warning caution' },
      { e: '🚫', k: 'prohibited no entry' },
      { e: '💤', k: 'zzz sleep' },
      { e: '♻️', k: 'recycle' },
      { e: '🔔', k: 'bell notification' },
      { e: '🔕', k: 'mute bell off' },
      { e: '🎵', k: 'music note' },
      { e: '🎶', k: 'music notes' },
      { e: '➡️', k: 'arrow right' },
      { e: '⬅️', k: 'arrow left' },
      { e: '⬆️', k: 'arrow up' },
      { e: '⬇️', k: 'arrow down' },
      { e: '🔄', k: 'refresh loop arrows' },
      { e: '🔝', k: 'top arrow' },
      { e: '🆗', k: 'ok button' },
      { e: '🆕', k: 'new button' },
      { e: '🆒', k: 'cool button' },
      { e: '🔞', k: 'no under 18' },
      { e: '⭕', k: 'circle red' },
      { e: '🟢', k: 'green circle' },
      { e: '🔴', k: 'red circle' },
      { e: '🟡', k: 'yellow circle' },
      { e: '🔵', k: 'blue circle' },
      { e: '⚫', k: 'black circle' },
      { e: '⚪', k: 'white circle' },
      { e: '🌐', k: 'globe web internet' },
      { e: '✨', k: 'sparkles shine' },
    ],
  },
  {
    key: 'flags',
    icon: 'pi pi-flag',
    items: [
      { e: '🏁', k: 'checkered flag finish race' },
      { e: '🚩', k: 'triangular flag' },
      { e: '🎌', k: 'crossed flags' },
      { e: '🏴', k: 'black flag' },
      { e: '🏳️', k: 'white flag' },
      { e: '🏳️‍🌈', k: 'rainbow pride flag' },
      { e: '🏴‍☠️', k: 'pirate flag' },
      { e: '🇦🇷', k: 'argentina' },
      { e: '🇧🇷', k: 'brazil' },
      { e: '🇨🇦', k: 'canada' },
      { e: '🇩🇪', k: 'germany' },
      { e: '🇪🇸', k: 'spain' },
      { e: '🇫🇷', k: 'france' },
      { e: '🇬🇧', k: 'uk britain england' },
      { e: '🇮🇹', k: 'italy' },
      { e: '🇯🇵', k: 'japan' },
      { e: '🇲🇽', k: 'mexico' },
      { e: '🇳🇱', k: 'netherlands' },
      { e: '🇵🇹', k: 'portugal' },
      { e: '🇺🇸', k: 'usa america united states' },
      { e: '🇺🇾', k: 'uruguay' },
      { e: '🇧🇪', k: 'belgium' },
      { e: '🇭🇷', k: 'croatia' },
      { e: '🇨🇭', k: 'switzerland' },
      { e: '🇰🇷', k: 'south korea' },
      { e: '🇸🇦', k: 'saudi arabia' },
      { e: '🇲🇦', k: 'morocco' },
      { e: '🇸🇳', k: 'senegal' },
      { e: '🇦🇺', k: 'australia' },
      { e: '🇹🇭', k: 'thailand' },
    ],
  },
]

// Flat list for searching across every category at once.
export const ALL_EMOJI: EmojiItem[] = EMOJI_CATEGORIES.flatMap((c) => c.items)

export function searchEmoji(query: string): EmojiItem[] {
  const q = query.trim().toLowerCase()
  if (!q) return ALL_EMOJI
  return ALL_EMOJI.filter((it) => it.k.includes(q))
}
