// GENERATED by tool/gen_models.dart from the OpenAPI snapshot - do not edit.
// Regenerate with tool/gen_models.sh; CI fails if this is stale.
//
// ignore_for_file: type=lint

class Bookmaker {
  final String key;
  final String title;
  final double home;
  final double draw;
  final double away;

  const Bookmaker({
    required this.key,
    required this.title,
    required this.home,
    required this.draw,
    required this.away,
  });

  factory Bookmaker.fromJson(Map<String, dynamic> json) => Bookmaker(
        key: json['key'] as String,
        title: json['title'] as String,
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
      );
}

class Competition {
  final String id;
  final String slug;
  final String name;

  const Competition({
    required this.id,
    required this.slug,
    required this.name,
  });

  factory Competition.fromJson(Map<String, dynamic> json) => Competition(
        id: json['id'] as String,
        slug: json['slug'] as String,
        name: json['name'] as String,
      );
}

class Competition2 {
  final String id;
  final String slug;
  final String name;

  const Competition2({
    required this.id,
    required this.slug,
    required this.name,
  });

  factory Competition2.fromJson(Map<String, dynamic> json) => Competition2(
        id: json['id'] as String,
        slug: json['slug'] as String,
        name: json['name'] as String,
      );
}

class CompetitionsResponse {
  final List<Competition> competitions;

  const CompetitionsResponse({
    required this.competitions,
  });

  factory CompetitionsResponse.fromJson(Map<String, dynamic> json) =>
      CompetitionsResponse(
        competitions: (json['competitions'] as List)
            .map((e) => Competition.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class Group {
  final String group;
  final List<Row> rows;

  const Group({
    required this.group,
    required this.rows,
  });

  factory Group.fromJson(Map<String, dynamic> json) => Group(
        group: json['group'] as String,
        rows: (json['rows'] as List)
            .map((e) => Row.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class Initial {
  final double home;
  final double draw;
  final double away;

  const Initial({
    required this.home,
    required this.draw,
    required this.away,
  });

  factory Initial.fromJson(Map<String, dynamic> json) => Initial(
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
      );
}

class LeaderboardResponse {
  final Competition2? competition;
  final League? league;
  final bool? live;
  final double? hiddenCount;
  final List<Row2> rows;

  const LeaderboardResponse({
    this.competition,
    this.league,
    this.live,
    this.hiddenCount,
    required this.rows,
  });

  factory LeaderboardResponse.fromJson(Map<String, dynamic> json) =>
      LeaderboardResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        league: json['league'] == null
            ? null
            : League.fromJson(json['league'] as Map<String, dynamic>),
        live: json['live'] as bool?,
        hiddenCount: (json['hiddenCount'] as num?)?.toDouble(),
        rows: (json['rows'] as List)
            .map((e) => Row2.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class League {
  final String id;
  final String name;

  const League({
    required this.id,
    required this.name,
  });

  factory League.fromJson(Map<String, dynamic> json) => League(
        id: json['id'] as String,
        name: json['name'] as String,
      );
}

class Match {
  final String id;
  final String competitionId;
  final String providerMatchId;

  /// One of: GROUP, R32, R16, QF, SF, THIRD_PLACE, FINAL.
  final String stage;
  final String? group;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;

  /// One of: SCHEDULED, LIVE, PAUSED, FINISHED, POSTPONED, CANCELLED, SUSPENDED, AWARDED, INTERRUPTED.
  final String status;
  final int? fullTimeHome;
  final int? fullTimeAway;
  final int? penaltiesHome;
  final int? penaltiesAway;

  /// One of: HOME, DRAW, AWAY.
  final String? winner;

  /// One of: PENDING, SCORED, VOID, STALE.
  final String scoringState;
  final String roundId;
  final String roundLabel;
  final int? matchday;
  final int roundSortOrder;
  final Odd? odds;
  final bool isLocked;

  const Match({
    required this.id,
    required this.competitionId,
    required this.providerMatchId,
    required this.stage,
    this.group,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    this.winner,
    required this.scoringState,
    required this.roundId,
    required this.roundLabel,
    this.matchday,
    required this.roundSortOrder,
    this.odds,
    required this.isLocked,
  });

  factory Match.fromJson(Map<String, dynamic> json) => Match(
        id: json['id'] as String,
        competitionId: json['competitionId'] as String,
        providerMatchId: json['providerMatchId'] as String,
        stage: json['stage'] as String,
        group: json['group'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        fullTimeHome: json['fullTimeHome'] as int?,
        fullTimeAway: json['fullTimeAway'] as int?,
        penaltiesHome: json['penaltiesHome'] as int?,
        penaltiesAway: json['penaltiesAway'] as int?,
        winner: json['winner'] as String?,
        scoringState: json['scoringState'] as String,
        roundId: json['roundId'] as String,
        roundLabel: json['roundLabel'] as String,
        matchday: json['matchday'] as int?,
        roundSortOrder: json['roundSortOrder'] as int,
        odds: json['odds'] == null
            ? null
            : Odd.fromJson(json['odds'] as Map<String, dynamic>),
        isLocked: json['isLocked'] as bool,
      );
}

class Match2 {
  final String id;
  final String competitionId;
  final String providerMatchId;

  /// One of: GROUP, R32, R16, QF, SF, THIRD_PLACE, FINAL.
  final String stage;
  final String? group;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;

  /// One of: SCHEDULED, LIVE, PAUSED, FINISHED, POSTPONED, CANCELLED, SUSPENDED, AWARDED, INTERRUPTED.
  final String status;
  final int? fullTimeHome;
  final int? fullTimeAway;
  final int? penaltiesHome;
  final int? penaltiesAway;

  /// One of: HOME, DRAW, AWAY.
  final String? winner;

  /// One of: PENDING, SCORED, VOID, STALE.
  final String scoringState;
  final String roundId;
  final String roundLabel;
  final int? matchday;
  final int roundSortOrder;

  const Match2({
    required this.id,
    required this.competitionId,
    required this.providerMatchId,
    required this.stage,
    this.group,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    this.winner,
    required this.scoringState,
    required this.roundId,
    required this.roundLabel,
    this.matchday,
    required this.roundSortOrder,
  });

  factory Match2.fromJson(Map<String, dynamic> json) => Match2(
        id: json['id'] as String,
        competitionId: json['competitionId'] as String,
        providerMatchId: json['providerMatchId'] as String,
        stage: json['stage'] as String,
        group: json['group'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        fullTimeHome: json['fullTimeHome'] as int?,
        fullTimeAway: json['fullTimeAway'] as int?,
        penaltiesHome: json['penaltiesHome'] as int?,
        penaltiesAway: json['penaltiesAway'] as int?,
        winner: json['winner'] as String?,
        scoringState: json['scoringState'] as String,
        roundId: json['roundId'] as String,
        roundLabel: json['roundLabel'] as String,
        matchday: json['matchday'] as int?,
        roundSortOrder: json['roundSortOrder'] as int,
      );
}

class MatchDetailResponse {
  final Match2 match;
  final MyPrediction? myPrediction;
  final Odd? odds;
  final bool isLocked;

  const MatchDetailResponse({
    required this.match,
    this.myPrediction,
    this.odds,
    required this.isLocked,
  });

  factory MatchDetailResponse.fromJson(Map<String, dynamic> json) =>
      MatchDetailResponse(
        match: Match2.fromJson(json['match'] as Map<String, dynamic>),
        myPrediction: json['myPrediction'] == null
            ? null
            : MyPrediction.fromJson(
                json['myPrediction'] as Map<String, dynamic>),
        odds: json['odds'] == null
            ? null
            : Odd.fromJson(json['odds'] as Map<String, dynamic>),
        isLocked: json['isLocked'] as bool,
      );
}

class MatchesResponse {
  final Competition2? competition;
  final List<Match> matches;

  const MatchesResponse({
    this.competition,
    required this.matches,
  });

  factory MatchesResponse.fromJson(Map<String, dynamic> json) =>
      MatchesResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        matches: (json['matches'] as List)
            .map((e) => Match.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class MyPrediction {
  final String id;
  final String userId;
  final String matchId;
  final String roundId;
  final int homeGoals;
  final int awayGoals;
  final bool isOutcomeOnly;
  final int? wager;
  final bool isJoker;
  final DateTime? lockedAt;
  final int? basePoints;

  /// One of: EXACT, DIFF, OUTCOME, MISS.
  final String? baseTier;
  final int? bonusPoints;

  /// One of: NONE, CROWD, ODDS.
  final String? bonusSource;
  final String? crowdShare;
  final String? jokerMultiplierApplied;
  final int? totalPoints;
  final int? scoredAtVersion;
  final DateTime? scoredAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  const MyPrediction({
    required this.id,
    required this.userId,
    required this.matchId,
    required this.roundId,
    required this.homeGoals,
    required this.awayGoals,
    required this.isOutcomeOnly,
    this.wager,
    required this.isJoker,
    this.lockedAt,
    this.basePoints,
    this.baseTier,
    this.bonusPoints,
    this.bonusSource,
    this.crowdShare,
    this.jokerMultiplierApplied,
    this.totalPoints,
    this.scoredAtVersion,
    this.scoredAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory MyPrediction.fromJson(Map<String, dynamic> json) => MyPrediction(
        id: json['id'] as String,
        userId: json['userId'] as String,
        matchId: json['matchId'] as String,
        roundId: json['roundId'] as String,
        homeGoals: json['homeGoals'] as int,
        awayGoals: json['awayGoals'] as int,
        isOutcomeOnly: json['isOutcomeOnly'] as bool,
        wager: json['wager'] as int?,
        isJoker: json['isJoker'] as bool,
        lockedAt: json['lockedAt'] == null
            ? null
            : DateTime.parse(json['lockedAt'] as String),
        basePoints: json['basePoints'] as int?,
        baseTier: json['baseTier'] as String?,
        bonusPoints: json['bonusPoints'] as int?,
        bonusSource: json['bonusSource'] as String?,
        crowdShare: json['crowdShare'] as String?,
        jokerMultiplierApplied: json['jokerMultiplierApplied'] as String?,
        totalPoints: json['totalPoints'] as int?,
        scoredAtVersion: json['scoredAtVersion'] as int?,
        scoredAt: json['scoredAt'] == null
            ? null
            : DateTime.parse(json['scoredAt'] as String),
        createdAt: DateTime.parse(json['createdAt'] as String),
        updatedAt: DateTime.parse(json['updatedAt'] as String),
      );
}

class Odd {
  final double home;
  final double draw;
  final double away;
  final DateTime fetchedAt;
  final Initial? initial;
  final List<Bookmaker>? bookmakers;

  const Odd({
    required this.home,
    required this.draw,
    required this.away,
    required this.fetchedAt,
    this.initial,
    this.bookmakers,
  });

  factory Odd.fromJson(Map<String, dynamic> json) => Odd(
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
        fetchedAt: DateTime.parse(json['fetchedAt'] as String),
        initial: json['initial'] == null
            ? null
            : Initial.fromJson(json['initial'] as Map<String, dynamic>),
        bookmakers: json['bookmakers'] == null
            ? null
            : (json['bookmakers'] as List)
                .map((e) => Bookmaker.fromJson(e as Map<String, dynamic>))
                .toList(),
      );
}

class PredictionInput {
  final int home;
  final int away;
  final bool? isOutcomeOnly;
  final int? wager;

  const PredictionInput({
    required this.home,
    required this.away,
    this.isOutcomeOnly,
    this.wager,
  });

  factory PredictionInput.fromJson(Map<String, dynamic> json) =>
      PredictionInput(
        home: json['home'] as int,
        away: json['away'] as int,
        isOutcomeOnly: json['isOutcomeOnly'] as bool?,
        wager: json['wager'] as int?,
      );
}

class PredictionSaveResponse {
  final String id;

  const PredictionSaveResponse({
    required this.id,
  });

  factory PredictionSaveResponse.fromJson(Map<String, dynamic> json) =>
      PredictionSaveResponse(
        id: json['id'] as String,
      );
}

class Row {
  final String? code;
  final String name;
  final double played;
  final double won;
  final double drawn;
  final double lost;
  final double gf;
  final double ga;
  final double gd;
  final double points;

  const Row({
    this.code,
    required this.name,
    required this.played,
    required this.won,
    required this.drawn,
    required this.lost,
    required this.gf,
    required this.ga,
    required this.gd,
    required this.points,
  });

  factory Row.fromJson(Map<String, dynamic> json) => Row(
        code: json['code'] as String?,
        name: json['name'] as String,
        played: (json['played'] as num).toDouble(),
        won: (json['won'] as num).toDouble(),
        drawn: (json['drawn'] as num).toDouble(),
        lost: (json['lost'] as num).toDouble(),
        gf: (json['gf'] as num).toDouble(),
        ga: (json['ga'] as num).toDouble(),
        gd: (json['gd'] as num).toDouble(),
        points: (json['points'] as num).toDouble(),
      );
}

class Row2 {
  final double rank;
  final String userId;
  final String displayName;
  final String? image;
  final double totalPoints;
  final double predictionPoints;
  final double championPoints;
  final String? championCode;
  final String? championName;
  final double bestScorerPoints;
  final String? bestScorerName;
  final String? bestScorerCode;
  final double livePoints;
  final double exactCount;
  final double outcomeCount;
  final double gdCount;
  final List<Showcase> showcase;
  final double? movement;

  const Row2({
    required this.rank,
    required this.userId,
    required this.displayName,
    this.image,
    required this.totalPoints,
    required this.predictionPoints,
    required this.championPoints,
    this.championCode,
    this.championName,
    required this.bestScorerPoints,
    this.bestScorerName,
    this.bestScorerCode,
    required this.livePoints,
    required this.exactCount,
    required this.outcomeCount,
    required this.gdCount,
    required this.showcase,
    this.movement,
  });

  factory Row2.fromJson(Map<String, dynamic> json) => Row2(
        rank: (json['rank'] as num).toDouble(),
        userId: json['userId'] as String,
        displayName: json['displayName'] as String,
        image: json['image'] as String?,
        totalPoints: (json['totalPoints'] as num).toDouble(),
        predictionPoints: (json['predictionPoints'] as num).toDouble(),
        championPoints: (json['championPoints'] as num).toDouble(),
        championCode: json['championCode'] as String?,
        championName: json['championName'] as String?,
        bestScorerPoints: (json['bestScorerPoints'] as num).toDouble(),
        bestScorerName: json['bestScorerName'] as String?,
        bestScorerCode: json['bestScorerCode'] as String?,
        livePoints: (json['livePoints'] as num).toDouble(),
        exactCount: (json['exactCount'] as num).toDouble(),
        outcomeCount: (json['outcomeCount'] as num).toDouble(),
        gdCount: (json['gdCount'] as num).toDouble(),
        showcase: (json['showcase'] as List)
            .map((e) => Showcase.fromJson(e as Map<String, dynamic>))
            .toList(),
        movement: (json['movement'] as num?)?.toDouble(),
      );
}

class Scorer {
  final String playerName;
  final String teamName;
  final String? teamCode;
  final double goals;
  final double? assists;
  final double? penalties;

  const Scorer({
    required this.playerName,
    required this.teamName,
    this.teamCode,
    required this.goals,
    this.assists,
    this.penalties,
  });

  factory Scorer.fromJson(Map<String, dynamic> json) => Scorer(
        playerName: json['playerName'] as String,
        teamName: json['teamName'] as String,
        teamCode: json['teamCode'] as String?,
        goals: (json['goals'] as num).toDouble(),
        assists: (json['assists'] as num?)?.toDouble(),
        penalties: (json['penalties'] as num?)?.toDouble(),
      );
}

class ScorersResponse {
  final List<Scorer> scorers;
  final List<Scorer> assists;

  const ScorersResponse({
    required this.scorers,
    required this.assists,
  });

  factory ScorersResponse.fromJson(Map<String, dynamic> json) =>
      ScorersResponse(
        scorers: (json['scorers'] as List)
            .map((e) => Scorer.fromJson(e as Map<String, dynamic>))
            .toList(),
        assists: (json['assists'] as List)
            .map((e) => Scorer.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class Showcase {
  final String key;
  final String category;

  /// One of: BRONZE, SILVER, GOLD, DIAMOND.
  final String? tier;

  const Showcase({
    required this.key,
    required this.category,
    this.tier,
  });

  factory Showcase.fromJson(Map<String, dynamic> json) => Showcase(
        key: json['key'] as String,
        category: json['category'] as String,
        tier: json['tier'] as String?,
      );
}

class StandingsResponse {
  final List<Group> groups;

  const StandingsResponse({
    required this.groups,
  });

  factory StandingsResponse.fromJson(Map<String, dynamic> json) =>
      StandingsResponse(
        groups: (json['groups'] as List)
            .map((e) => Group.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class TrustStatusResponse {
  final bool trusted;

  const TrustStatusResponse({
    required this.trusted,
  });

  factory TrustStatusResponse.fromJson(Map<String, dynamic> json) =>
      TrustStatusResponse(
        trusted: json['trusted'] as bool,
      );
}
