// GENERATED by tool/gen_models.dart from the OpenAPI snapshot - do not edit.
// Regenerate with tool/gen_models.sh; CI fails if this is stale.
//
// ignore_for_file: type=lint

class AnalyticsResponse {
  final String competitionName;
  final bool hasData;
  final double totalPicks;
  final double totalPoints;
  final double avgPoints;
  final Tier tiers;
  final double accuracy;
  final double exactRate;
  final Goal goals;
  final OutcomeLean outcomeLean;
  final Team teams;
  final List<OverTime> overTime;
  final Streak streak;
  final BestCall? bestCall;
  final BestCall? worstMiss;
  final FergieTime fergieTime;

  const AnalyticsResponse({
    required this.competitionName,
    required this.hasData,
    required this.totalPicks,
    required this.totalPoints,
    required this.avgPoints,
    required this.tiers,
    required this.accuracy,
    required this.exactRate,
    required this.goals,
    required this.outcomeLean,
    required this.teams,
    required this.overTime,
    required this.streak,
    this.bestCall,
    this.worstMiss,
    required this.fergieTime,
  });

  factory AnalyticsResponse.fromJson(Map<String, dynamic> json) =>
      AnalyticsResponse(
        competitionName: json['competitionName'] as String,
        hasData: json['hasData'] as bool,
        totalPicks: (json['totalPicks'] as num).toDouble(),
        totalPoints: (json['totalPoints'] as num).toDouble(),
        avgPoints: (json['avgPoints'] as num).toDouble(),
        tiers: Tier.fromJson(json['tiers'] as Map<String, dynamic>),
        accuracy: (json['accuracy'] as num).toDouble(),
        exactRate: (json['exactRate'] as num).toDouble(),
        goals: Goal.fromJson(json['goals'] as Map<String, dynamic>),
        outcomeLean:
            OutcomeLean.fromJson(json['outcomeLean'] as Map<String, dynamic>),
        teams: Team.fromJson(json['teams'] as Map<String, dynamic>),
        overTime: (json['overTime'] as List)
            .map((e) => OverTime.fromJson(e as Map<String, dynamic>))
            .toList(),
        streak: Streak.fromJson(json['streak'] as Map<String, dynamic>),
        bestCall: json['bestCall'] == null
            ? null
            : BestCall.fromJson(json['bestCall'] as Map<String, dynamic>),
        worstMiss: json['worstMiss'] == null
            ? null
            : BestCall.fromJson(json['worstMiss'] as Map<String, dynamic>),
        fergieTime:
            FergieTime.fromJson(json['fergieTime'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'competitionName': competitionName,
        'hasData': hasData,
        'totalPicks': totalPicks,
        'totalPoints': totalPoints,
        'avgPoints': avgPoints,
        'tiers': tiers.toJson(),
        'accuracy': accuracy,
        'exactRate': exactRate,
        'goals': goals.toJson(),
        'outcomeLean': outcomeLean.toJson(),
        'teams': teams.toJson(),
        'overTime': overTime.map((e) => e.toJson()).toList(),
        'streak': streak.toJson(),
        'bestCall': bestCall?.toJson(),
        'worstMiss': worstMiss?.toJson(),
        'fergieTime': fergieTime.toJson(),
      };
}

class Attachment {
  final double idx;
  final double epoch;

  const Attachment({
    required this.idx,
    required this.epoch,
  });

  factory Attachment.fromJson(Map<String, dynamic> json) => Attachment(
        idx: (json['idx'] as num).toDouble(),
        epoch: (json['epoch'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'idx': idx,
        'epoch': epoch,
      };
}

class BestCall {
  final String home;
  final String away;
  final String? homeCode;
  final String? awayCode;
  final String predicted;
  final String actual;
  final double points;
  final String tier;
  final bool isJoker;

  const BestCall({
    required this.home,
    required this.away,
    this.homeCode,
    this.awayCode,
    required this.predicted,
    required this.actual,
    required this.points,
    required this.tier,
    required this.isJoker,
  });

  factory BestCall.fromJson(Map<String, dynamic> json) => BestCall(
        home: json['home'] as String,
        away: json['away'] as String,
        homeCode: json['homeCode'] as String?,
        awayCode: json['awayCode'] as String?,
        predicted: json['predicted'] as String,
        actual: json['actual'] as String,
        points: (json['points'] as num).toDouble(),
        tier: json['tier'] as String,
        isJoker: json['isJoker'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'away': away,
        'homeCode': homeCode,
        'awayCode': awayCode,
        'predicted': predicted,
        'actual': actual,
        'points': points,
        'tier': tier,
        'isJoker': isJoker,
      };
}

class BestScorerResponse {
  final Competition2? competition;
  final String? provider;
  final String? season;
  final double bonus;
  final List<Team3> teams;
  final MyPick2? myPick;
  final bool locked;
  final SecondChance secondChance;

  const BestScorerResponse({
    this.competition,
    this.provider,
    this.season,
    required this.bonus,
    required this.teams,
    this.myPick,
    required this.locked,
    required this.secondChance,
  });

  factory BestScorerResponse.fromJson(Map<String, dynamic> json) =>
      BestScorerResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        provider: json['provider'] as String?,
        season: json['season'] as String?,
        bonus: (json['bonus'] as num).toDouble(),
        teams: (json['teams'] as List)
            .map((e) => Team3.fromJson(e as Map<String, dynamic>))
            .toList(),
        myPick: json['myPick'] == null
            ? null
            : MyPick2.fromJson(json['myPick'] as Map<String, dynamic>),
        locked: json['locked'] as bool,
        secondChance:
            SecondChance.fromJson(json['secondChance'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'competition': competition?.toJson(),
        'provider': provider,
        'season': season,
        'bonus': bonus,
        'teams': teams.map((e) => e.toJson()).toList(),
        'myPick': myPick?.toJson(),
        'locked': locked,
        'secondChance': secondChance.toJson(),
      };
}

class BiggestGain {
  final String home;
  final String away;
  final String? homeCode;
  final String? awayCode;
  final String predicted;
  final String actual;
  final double gained;
  final double lost;
  final double net;
  final bool isJoker;

  const BiggestGain({
    required this.home,
    required this.away,
    this.homeCode,
    this.awayCode,
    required this.predicted,
    required this.actual,
    required this.gained,
    required this.lost,
    required this.net,
    required this.isJoker,
  });

  factory BiggestGain.fromJson(Map<String, dynamic> json) => BiggestGain(
        home: json['home'] as String,
        away: json['away'] as String,
        homeCode: json['homeCode'] as String?,
        awayCode: json['awayCode'] as String?,
        predicted: json['predicted'] as String,
        actual: json['actual'] as String,
        gained: (json['gained'] as num).toDouble(),
        lost: (json['lost'] as num).toDouble(),
        net: (json['net'] as num).toDouble(),
        isJoker: json['isJoker'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'away': away,
        'homeCode': homeCode,
        'awayCode': awayCode,
        'predicted': predicted,
        'actual': actual,
        'gained': gained,
        'lost': lost,
        'net': net,
        'isJoker': isJoker,
      };
}

class Board {
  /// One of: points, survival.
  final String kind;

  /// One of: NORMAL, EASY, HARD, HARDCORE.
  final String mode;
  final bool live;
  final List<dynamic> rows;

  const Board({
    required this.kind,
    required this.mode,
    required this.live,
    required this.rows,
  });

  factory Board.fromJson(Map<String, dynamic> json) => Board(
        kind: json['kind'] as String,
        mode: json['mode'] as String,
        live: json['live'] as bool,
        rows: (json['rows'] as List).map((e) => e as dynamic).toList(),
      );

  Map<String, dynamic> toJson() => {
        'kind': kind,
        'mode': mode,
        'live': live,
        'rows': rows,
      };
}

class Bookmaker {
  final String key;
  final String title;
  final double home;
  final double draw;
  final double away;

  const Bookmaker({
    required this.key,
    required this.title,
    required this.home,
    required this.draw,
    required this.away,
  });

  factory Bookmaker.fromJson(Map<String, dynamic> json) => Bookmaker(
        key: json['key'] as String,
        title: json['title'] as String,
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'key': key,
        'title': title,
        'home': home,
        'draw': draw,
        'away': away,
      };
}

class BotPredictionsResponse {
  final PredictionSaveResponse bot;

  /// One of: consensus, evil-twin, equalizer.
  final String persona;
  final Competition competition;
  final League4? league;
  final Champion? champion;
  final Summary summary;
  final Subject? subject;
  final bool admin;

  /// One of: MODE, MEAN.
  final String method;
  final bool modeAvailable;
  final double population;
  final List<Prediction2> predictions;

  const BotPredictionsResponse({
    required this.bot,
    required this.persona,
    required this.competition,
    this.league,
    this.champion,
    required this.summary,
    this.subject,
    required this.admin,
    required this.method,
    required this.modeAvailable,
    required this.population,
    required this.predictions,
  });

  factory BotPredictionsResponse.fromJson(Map<String, dynamic> json) =>
      BotPredictionsResponse(
        bot: PredictionSaveResponse.fromJson(
            json['bot'] as Map<String, dynamic>),
        persona: json['persona'] as String,
        competition:
            Competition.fromJson(json['competition'] as Map<String, dynamic>),
        league: json['league'] == null
            ? null
            : League4.fromJson(json['league'] as Map<String, dynamic>),
        champion: json['champion'] == null
            ? null
            : Champion.fromJson(json['champion'] as Map<String, dynamic>),
        summary: Summary.fromJson(json['summary'] as Map<String, dynamic>),
        subject: json['subject'] == null
            ? null
            : Subject.fromJson(json['subject'] as Map<String, dynamic>),
        admin: json['admin'] as bool,
        method: json['method'] as String,
        modeAvailable: json['modeAvailable'] as bool,
        population: (json['population'] as num).toDouble(),
        predictions: (json['predictions'] as List)
            .map((e) => Prediction2.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'bot': bot.toJson(),
        'persona': persona,
        'competition': competition.toJson(),
        'league': league?.toJson(),
        'champion': champion?.toJson(),
        'summary': summary.toJson(),
        'subject': subject?.toJson(),
        'admin': admin,
        'method': method,
        'modeAvailable': modeAvailable,
        'population': population,
        'predictions': predictions.map((e) => e.toJson()).toList(),
      };
}

class Breakdown {
  final String home;
  final String away;
  final String? homeCode;
  final String? awayCode;
  final String predicted;
  final String actual;
  final double gained;
  final double lost;
  final double net;
  final bool isJoker;

  const Breakdown({
    required this.home,
    required this.away,
    this.homeCode,
    this.awayCode,
    required this.predicted,
    required this.actual,
    required this.gained,
    required this.lost,
    required this.net,
    required this.isJoker,
  });

  factory Breakdown.fromJson(Map<String, dynamic> json) => Breakdown(
        home: json['home'] as String,
        away: json['away'] as String,
        homeCode: json['homeCode'] as String?,
        awayCode: json['awayCode'] as String?,
        predicted: json['predicted'] as String,
        actual: json['actual'] as String,
        gained: (json['gained'] as num).toDouble(),
        lost: (json['lost'] as num).toDouble(),
        net: (json['net'] as num).toDouble(),
        isJoker: json['isJoker'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'away': away,
        'homeCode': homeCode,
        'awayCode': awayCode,
        'predicted': predicted,
        'actual': actual,
        'gained': gained,
        'lost': lost,
        'net': net,
        'isJoker': isJoker,
      };
}

class Champion {
  final String teamCode;
  final String teamName;
  final double count;
  final double total;
  final double awardedPoints;

  const Champion({
    required this.teamCode,
    required this.teamName,
    required this.count,
    required this.total,
    required this.awardedPoints,
  });

  factory Champion.fromJson(Map<String, dynamic> json) => Champion(
        teamCode: json['teamCode'] as String,
        teamName: json['teamName'] as String,
        count: (json['count'] as num).toDouble(),
        total: (json['total'] as num).toDouble(),
        awardedPoints: (json['awardedPoints'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'teamCode': teamCode,
        'teamName': teamName,
        'count': count,
        'total': total,
        'awardedPoints': awardedPoints,
      };
}

class ChampionResponse {
  final Competition2? competition;
  final List<Team2> teams;
  final MyPick? myPick;
  final bool locked;
  final SecondChance secondChance;

  const ChampionResponse({
    this.competition,
    required this.teams,
    this.myPick,
    required this.locked,
    required this.secondChance,
  });

  factory ChampionResponse.fromJson(Map<String, dynamic> json) =>
      ChampionResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        teams: (json['teams'] as List)
            .map((e) => Team2.fromJson(e as Map<String, dynamic>))
            .toList(),
        myPick: json['myPick'] == null
            ? null
            : MyPick.fromJson(json['myPick'] as Map<String, dynamic>),
        locked: json['locked'] as bool,
        secondChance:
            SecondChance.fromJson(json['secondChance'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'competition': competition?.toJson(),
        'teams': teams.map((e) => e.toJson()).toList(),
        'myPick': myPick?.toJson(),
        'locked': locked,
        'secondChance': secondChance.toJson(),
      };
}

class ChatIdentityResponse {
  final Identity? identity;

  const ChatIdentityResponse({
    this.identity,
  });

  factory ChatIdentityResponse.fromJson(Map<String, dynamic> json) =>
      ChatIdentityResponse(
        identity: json['identity'] == null
            ? null
            : Identity.fromJson(json['identity'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'identity': identity?.toJson(),
      };
}

class ChatMessagesResponse {
  final List<Message> messages;
  final String? readMarker;

  const ChatMessagesResponse({
    required this.messages,
    this.readMarker,
  });

  factory ChatMessagesResponse.fromJson(Map<String, dynamic> json) =>
      ChatMessagesResponse(
        messages: (json['messages'] as List)
            .map((e) => Message.fromJson(e as Map<String, dynamic>))
            .toList(),
        readMarker: json['readMarker'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'messages': messages.map((e) => e.toJson()).toList(),
        'readMarker': readMarker,
      };
}

class ChatStatusResponse {
  final bool enabled;
  final double epoch;
  final String role;
  final List<MyWrappedKey> myWrappedKeys;
  final List<MissingKey> missingKeys;
  final List<MissingKey> memberKeys;
  final bool rekeyPending;

  const ChatStatusResponse({
    required this.enabled,
    required this.epoch,
    required this.role,
    required this.myWrappedKeys,
    required this.missingKeys,
    required this.memberKeys,
    required this.rekeyPending,
  });

  factory ChatStatusResponse.fromJson(Map<String, dynamic> json) =>
      ChatStatusResponse(
        enabled: json['enabled'] as bool,
        epoch: (json['epoch'] as num).toDouble(),
        role: json['role'] as String,
        myWrappedKeys: (json['myWrappedKeys'] as List)
            .map((e) => MyWrappedKey.fromJson(e as Map<String, dynamic>))
            .toList(),
        missingKeys: (json['missingKeys'] as List)
            .map((e) => MissingKey.fromJson(e as Map<String, dynamic>))
            .toList(),
        memberKeys: (json['memberKeys'] as List)
            .map((e) => MissingKey.fromJson(e as Map<String, dynamic>))
            .toList(),
        rekeyPending: json['rekeyPending'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'enabled': enabled,
        'epoch': epoch,
        'role': role,
        'myWrappedKeys': myWrappedKeys.map((e) => e.toJson()).toList(),
        'missingKeys': missingKeys.map((e) => e.toJson()).toList(),
        'memberKeys': memberKeys.map((e) => e.toJson()).toList(),
        'rekeyPending': rekeyPending,
      };
}

class CommitmentsResponse {
  final List<Entry> entries;
  final Head head;
  final double? nextSeq;

  const CommitmentsResponse({
    required this.entries,
    required this.head,
    this.nextSeq,
  });

  factory CommitmentsResponse.fromJson(Map<String, dynamic> json) =>
      CommitmentsResponse(
        entries: (json['entries'] as List)
            .map((e) => Entry.fromJson(e as Map<String, dynamic>))
            .toList(),
        head: Head.fromJson(json['head'] as Map<String, dynamic>),
        nextSeq: (json['nextSeq'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'entries': entries.map((e) => e.toJson()).toList(),
        'head': head.toJson(),
        'nextSeq': nextSeq,
      };
}

class Competition {
  final String id;
  final String slug;
  final String name;

  const Competition({
    required this.id,
    required this.slug,
    required this.name,
  });

  factory Competition.fromJson(Map<String, dynamic> json) => Competition(
        id: json['id'] as String,
        slug: json['slug'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'slug': slug,
        'name': name,
      };
}

class Competition2 {
  final String id;
  final String slug;
  final String name;

  const Competition2({
    required this.id,
    required this.slug,
    required this.name,
  });

  factory Competition2.fromJson(Map<String, dynamic> json) => Competition2(
        id: json['id'] as String,
        slug: json['slug'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'slug': slug,
        'name': name,
      };
}

class CompetitionsResponse {
  final List<Competition> competitions;

  const CompetitionsResponse({
    required this.competitions,
  });

  factory CompetitionsResponse.fromJson(Map<String, dynamic> json) =>
      CompetitionsResponse(
        competitions: (json['competitions'] as List)
            .map((e) => Competition.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'competitions': competitions.map((e) => e.toJson()).toList(),
      };
}

class DmRecipientsResponse {
  final List<Recipient> recipients;

  const DmRecipientsResponse({
    required this.recipients,
  });

  factory DmRecipientsResponse.fromJson(Map<String, dynamic> json) =>
      DmRecipientsResponse(
        recipients: (json['recipients'] as List)
            .map((e) => Recipient.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'recipients': recipients.map((e) => e.toJson()).toList(),
      };
}

class DmThreadResponse {
  final Thread2 thread;

  const DmThreadResponse({
    required this.thread,
  });

  factory DmThreadResponse.fromJson(Map<String, dynamic> json) =>
      DmThreadResponse(
        thread: Thread2.fromJson(json['thread'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'thread': thread.toJson(),
      };
}

class DmThreadsResponse {
  final List<Thread> threads;

  const DmThreadsResponse({
    required this.threads,
  });

  factory DmThreadsResponse.fromJson(Map<String, dynamic> json) =>
      DmThreadsResponse(
        threads: (json['threads'] as List)
            .map((e) => Thread.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'threads': threads.map((e) => e.toJson()).toList(),
      };
}

class Earlier {
  final double home;
  final double away;
  final double points;

  /// One of: EXACT, DIFF, OUTCOME, MISS.
  final String tier;

  const Earlier({
    required this.home,
    required this.away,
    required this.points,
    required this.tier,
  });

  factory Earlier.fromJson(Map<String, dynamic> json) => Earlier(
        home: (json['home'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
        points: (json['points'] as num).toDouble(),
        tier: json['tier'] as String,
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'away': away,
        'points': points,
        'tier': tier,
      };
}

class Entry {
  final double seq;
  final String prevHash;
  final String commitment;
  final String subject;
  final String matchId;
  final String createdAt;
  final String entryHash;
  final bool opened;
  final double? homeGoals;
  final double? awayGoals;
  final String? salt;

  const Entry({
    required this.seq,
    required this.prevHash,
    required this.commitment,
    required this.subject,
    required this.matchId,
    required this.createdAt,
    required this.entryHash,
    required this.opened,
    this.homeGoals,
    this.awayGoals,
    this.salt,
  });

  factory Entry.fromJson(Map<String, dynamic> json) => Entry(
        seq: (json['seq'] as num).toDouble(),
        prevHash: json['prevHash'] as String,
        commitment: json['commitment'] as String,
        subject: json['subject'] as String,
        matchId: json['matchId'] as String,
        createdAt: json['createdAt'] as String,
        entryHash: json['entryHash'] as String,
        opened: json['opened'] as bool,
        homeGoals: (json['homeGoals'] as num?)?.toDouble(),
        awayGoals: (json['awayGoals'] as num?)?.toDouble(),
        salt: json['salt'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'seq': seq,
        'prevHash': prevHash,
        'commitment': commitment,
        'subject': subject,
        'matchId': matchId,
        'createdAt': createdAt,
        'entryHash': entryHash,
        'opened': opened,
        'homeGoals': homeGoals,
        'awayGoals': awayGoals,
        'salt': salt,
      };
}

class FergieTime {
  final double matches;
  final double goals;
  final double netPoints;
  final double pointsWon;
  final double pointsLost;
  final BiggestGain? biggestGain;
  final BiggestGain? biggestLoss;
  final List<Breakdown> breakdown;

  const FergieTime({
    required this.matches,
    required this.goals,
    required this.netPoints,
    required this.pointsWon,
    required this.pointsLost,
    this.biggestGain,
    this.biggestLoss,
    required this.breakdown,
  });

  factory FergieTime.fromJson(Map<String, dynamic> json) => FergieTime(
        matches: (json['matches'] as num).toDouble(),
        goals: (json['goals'] as num).toDouble(),
        netPoints: (json['netPoints'] as num).toDouble(),
        pointsWon: (json['pointsWon'] as num).toDouble(),
        pointsLost: (json['pointsLost'] as num).toDouble(),
        biggestGain: json['biggestGain'] == null
            ? null
            : BiggestGain.fromJson(json['biggestGain'] as Map<String, dynamic>),
        biggestLoss: json['biggestLoss'] == null
            ? null
            : BiggestGain.fromJson(json['biggestLoss'] as Map<String, dynamic>),
        breakdown: (json['breakdown'] as List)
            .map((e) => Breakdown.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'matches': matches,
        'goals': goals,
        'netPoints': netPoints,
        'pointsWon': pointsWon,
        'pointsLost': pointsLost,
        'biggestGain': biggestGain?.toJson(),
        'biggestLoss': biggestLoss?.toJson(),
        'breakdown': breakdown.map((e) => e.toJson()).toList(),
      };
}

class Goal {
  final double predictedAvg;
  final double actualAvg;
  final double lean;

  const Goal({
    required this.predictedAvg,
    required this.actualAvg,
    required this.lean,
  });

  factory Goal.fromJson(Map<String, dynamic> json) => Goal(
        predictedAvg: (json['predictedAvg'] as num).toDouble(),
        actualAvg: (json['actualAvg'] as num).toDouble(),
        lean: (json['lean'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'predictedAvg': predictedAvg,
        'actualAvg': actualAvg,
        'lean': lean,
      };
}

class Group {
  final String group;
  final List<RowData> rows;

  const Group({
    required this.group,
    required this.rows,
  });

  factory Group.fromJson(Map<String, dynamic> json) => Group(
        group: json['group'] as String,
        rows: (json['rows'] as List)
            .map((e) => RowData.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'group': group,
        'rows': rows.map((e) => e.toJson()).toList(),
      };
}

class Head {
  final double seq;
  final String headHash;

  const Head({
    required this.seq,
    required this.headHash,
  });

  factory Head.fromJson(Map<String, dynamic> json) => Head(
        seq: (json['seq'] as num).toDouble(),
        headHash: json['headHash'] as String,
      );

  Map<String, dynamic> toJson() => {
        'seq': seq,
        'headHash': headHash,
      };
}

class Identity {
  final String publicKey;
  final bool hasRecovery;

  const Identity({
    required this.publicKey,
    required this.hasRecovery,
  });

  factory Identity.fromJson(Map<String, dynamic> json) => Identity(
        publicKey: json['publicKey'] as String,
        hasRecovery: json['hasRecovery'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'publicKey': publicKey,
        'hasRecovery': hasRecovery,
      };
}

class Initial {
  final double home;
  final double draw;
  final double away;

  const Initial({
    required this.home,
    required this.draw,
    required this.away,
  });

  factory Initial.fromJson(Map<String, dynamic> json) => Initial(
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'draw': draw,
        'away': away,
      };
}

class Item {
  final String id;
  final String title;
  final String? description;

  /// One of: PLANNED, IN_PROGRESS, SHIPPED, SUGGESTED.
  final String status;
  final int position;
  final double voteCount;
  final bool viewerHasVoted;
  final bool underReview;
  final DateTime updatedAt;

  const Item({
    required this.id,
    required this.title,
    this.description,
    required this.status,
    required this.position,
    required this.voteCount,
    required this.viewerHasVoted,
    required this.underReview,
    required this.updatedAt,
  });

  factory Item.fromJson(Map<String, dynamic> json) => Item(
        id: json['id'] as String,
        title: json['title'] as String,
        description: json['description'] as String?,
        status: json['status'] as String,
        position: json['position'] as int,
        voteCount: (json['voteCount'] as num).toDouble(),
        viewerHasVoted: json['viewerHasVoted'] as bool,
        underReview: json['underReview'] as bool,
        updatedAt: DateTime.parse(json['updatedAt'] as String),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'status': status,
        'position': position,
        'voteCount': voteCount,
        'viewerHasVoted': viewerHasVoted,
        'underReview': underReview,
        'updatedAt': updatedAt.toIso8601String(),
      };
}

class LeaderboardResponse {
  final Competition2? competition;
  final League? league;
  final bool? live;
  final double? hiddenCount;
  final List<RowData2> rows;

  const LeaderboardResponse({
    this.competition,
    this.league,
    this.live,
    this.hiddenCount,
    required this.rows,
  });

  factory LeaderboardResponse.fromJson(Map<String, dynamic> json) =>
      LeaderboardResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        league: json['league'] == null
            ? null
            : League.fromJson(json['league'] as Map<String, dynamic>),
        live: json['live'] as bool?,
        hiddenCount: (json['hiddenCount'] as num?)?.toDouble(),
        rows: (json['rows'] as List)
            .map((e) => RowData2.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'competition': competition?.toJson(),
        'league': league?.toJson(),
        'live': live,
        'hiddenCount': hiddenCount,
        'rows': rows.map((e) => e.toJson()).toList(),
      };
}

class League {
  final String id;
  final String name;

  const League({
    required this.id,
    required this.name,
  });

  factory League.fromJson(Map<String, dynamic> json) => League(
        id: json['id'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
      };
}

class League2 {
  final String id;
  final String name;

  /// One of: PRIVATE, PUBLIC.
  final String visibility;

  /// One of: NORMAL, EASY, HARD, HARDCORE.
  final String mode;
  final double? lives;

  /// One of: OWNER, MODERATOR, MEMBER.
  final String role;
  final bool picksSynced;
  final double memberCount;
  final bool chatEnabled;
  final Competition competition;
  final String? joinCode;

  const League2({
    required this.id,
    required this.name,
    required this.visibility,
    required this.mode,
    this.lives,
    required this.role,
    required this.picksSynced,
    required this.memberCount,
    required this.chatEnabled,
    required this.competition,
    this.joinCode,
  });

  factory League2.fromJson(Map<String, dynamic> json) => League2(
        id: json['id'] as String,
        name: json['name'] as String,
        visibility: json['visibility'] as String,
        mode: json['mode'] as String,
        lives: (json['lives'] as num?)?.toDouble(),
        role: json['role'] as String,
        picksSynced: json['picksSynced'] as bool,
        memberCount: (json['memberCount'] as num).toDouble(),
        chatEnabled: json['chatEnabled'] as bool,
        competition:
            Competition.fromJson(json['competition'] as Map<String, dynamic>),
        joinCode: json['joinCode'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'visibility': visibility,
        'mode': mode,
        'lives': lives,
        'role': role,
        'picksSynced': picksSynced,
        'memberCount': memberCount,
        'chatEnabled': chatEnabled,
        'competition': competition.toJson(),
        'joinCode': joinCode,
      };
}

class League3 {
  final String id;
  final String name;
  final double memberCount;

  const League3({
    required this.id,
    required this.name,
    required this.memberCount,
  });

  factory League3.fromJson(Map<String, dynamic> json) => League3(
        id: json['id'] as String,
        name: json['name'] as String,
        memberCount: (json['memberCount'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'memberCount': memberCount,
      };
}

class League4 {
  final String id;
  final String name;

  const League4({
    required this.id,
    required this.name,
  });

  factory League4.fromJson(Map<String, dynamic> json) => League4(
        id: json['id'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
      };
}

class LeaguesResponse {
  final List<League2> leagues;

  const LeaguesResponse({
    required this.leagues,
  });

  factory LeaguesResponse.fromJson(Map<String, dynamic> json) =>
      LeaguesResponse(
        leagues: (json['leagues'] as List)
            .map((e) => League2.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'leagues': leagues.map((e) => e.toJson()).toList(),
      };
}

class Match {
  final String id;
  final String competitionId;
  final String providerMatchId;

  /// One of: GROUP, R32, R16, QF, SF, THIRD_PLACE, FINAL.
  final String stage;
  final String? group;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;

  /// One of: SCHEDULED, LIVE, PAUSED, FINISHED, POSTPONED, CANCELLED, SUSPENDED, AWARDED, INTERRUPTED.
  final String status;
  final int? fullTimeHome;
  final int? fullTimeAway;
  final int? penaltiesHome;
  final int? penaltiesAway;

  /// One of: HOME, DRAW, AWAY.
  final String? winner;

  /// One of: PENDING, SCORED, VOID, STALE.
  final String scoringState;
  final String roundId;
  final String roundLabel;
  final int? matchday;
  final int roundSortOrder;
  final Odd? odds;
  final bool isLocked;

  const Match({
    required this.id,
    required this.competitionId,
    required this.providerMatchId,
    required this.stage,
    this.group,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    this.winner,
    required this.scoringState,
    required this.roundId,
    required this.roundLabel,
    this.matchday,
    required this.roundSortOrder,
    this.odds,
    required this.isLocked,
  });

  factory Match.fromJson(Map<String, dynamic> json) => Match(
        id: json['id'] as String,
        competitionId: json['competitionId'] as String,
        providerMatchId: json['providerMatchId'] as String,
        stage: json['stage'] as String,
        group: json['group'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        fullTimeHome: json['fullTimeHome'] as int?,
        fullTimeAway: json['fullTimeAway'] as int?,
        penaltiesHome: json['penaltiesHome'] as int?,
        penaltiesAway: json['penaltiesAway'] as int?,
        winner: json['winner'] as String?,
        scoringState: json['scoringState'] as String,
        roundId: json['roundId'] as String,
        roundLabel: json['roundLabel'] as String,
        matchday: json['matchday'] as int?,
        roundSortOrder: json['roundSortOrder'] as int,
        odds: json['odds'] == null
            ? null
            : Odd.fromJson(json['odds'] as Map<String, dynamic>),
        isLocked: json['isLocked'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'competitionId': competitionId,
        'providerMatchId': providerMatchId,
        'stage': stage,
        'group': group,
        'homeTeam': homeTeam,
        'awayTeam': awayTeam,
        'homeTeamCode': homeTeamCode,
        'awayTeamCode': awayTeamCode,
        'kickoffTime': kickoffTime.toIso8601String(),
        'status': status,
        'fullTimeHome': fullTimeHome,
        'fullTimeAway': fullTimeAway,
        'penaltiesHome': penaltiesHome,
        'penaltiesAway': penaltiesAway,
        'winner': winner,
        'scoringState': scoringState,
        'roundId': roundId,
        'roundLabel': roundLabel,
        'matchday': matchday,
        'roundSortOrder': roundSortOrder,
        'odds': odds?.toJson(),
        'isLocked': isLocked,
      };
}

class Match2 {
  final String id;
  final String competitionId;
  final String providerMatchId;

  /// One of: GROUP, R32, R16, QF, SF, THIRD_PLACE, FINAL.
  final String stage;
  final String? group;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;

  /// One of: SCHEDULED, LIVE, PAUSED, FINISHED, POSTPONED, CANCELLED, SUSPENDED, AWARDED, INTERRUPTED.
  final String status;
  final int? fullTimeHome;
  final int? fullTimeAway;
  final int? penaltiesHome;
  final int? penaltiesAway;

  /// One of: HOME, DRAW, AWAY.
  final String? winner;

  /// One of: PENDING, SCORED, VOID, STALE.
  final String scoringState;
  final String roundId;
  final String roundLabel;
  final int? matchday;
  final int roundSortOrder;

  const Match2({
    required this.id,
    required this.competitionId,
    required this.providerMatchId,
    required this.stage,
    this.group,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    this.winner,
    required this.scoringState,
    required this.roundId,
    required this.roundLabel,
    this.matchday,
    required this.roundSortOrder,
  });

  factory Match2.fromJson(Map<String, dynamic> json) => Match2(
        id: json['id'] as String,
        competitionId: json['competitionId'] as String,
        providerMatchId: json['providerMatchId'] as String,
        stage: json['stage'] as String,
        group: json['group'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        fullTimeHome: json['fullTimeHome'] as int?,
        fullTimeAway: json['fullTimeAway'] as int?,
        penaltiesHome: json['penaltiesHome'] as int?,
        penaltiesAway: json['penaltiesAway'] as int?,
        winner: json['winner'] as String?,
        scoringState: json['scoringState'] as String,
        roundId: json['roundId'] as String,
        roundLabel: json['roundLabel'] as String,
        matchday: json['matchday'] as int?,
        roundSortOrder: json['roundSortOrder'] as int,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'competitionId': competitionId,
        'providerMatchId': providerMatchId,
        'stage': stage,
        'group': group,
        'homeTeam': homeTeam,
        'awayTeam': awayTeam,
        'homeTeamCode': homeTeamCode,
        'awayTeamCode': awayTeamCode,
        'kickoffTime': kickoffTime.toIso8601String(),
        'status': status,
        'fullTimeHome': fullTimeHome,
        'fullTimeAway': fullTimeAway,
        'penaltiesHome': penaltiesHome,
        'penaltiesAway': penaltiesAway,
        'winner': winner,
        'scoringState': scoringState,
        'roundId': roundId,
        'roundLabel': roundLabel,
        'matchday': matchday,
        'roundSortOrder': roundSortOrder,
      };
}

class MatchDetailResponse {
  final Match2 match;
  final MyPrediction? myPrediction;
  final Odd? odds;
  final bool isLocked;

  const MatchDetailResponse({
    required this.match,
    this.myPrediction,
    this.odds,
    required this.isLocked,
  });

  factory MatchDetailResponse.fromJson(Map<String, dynamic> json) =>
      MatchDetailResponse(
        match: Match2.fromJson(json['match'] as Map<String, dynamic>),
        myPrediction: json['myPrediction'] == null
            ? null
            : MyPrediction.fromJson(
                json['myPrediction'] as Map<String, dynamic>),
        odds: json['odds'] == null
            ? null
            : Odd.fromJson(json['odds'] as Map<String, dynamic>),
        isLocked: json['isLocked'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'match': match.toJson(),
        'myPrediction': myPrediction?.toJson(),
        'odds': odds?.toJson(),
        'isLocked': isLocked,
      };
}

class MatchesResponse {
  final Competition2? competition;
  final List<Match> matches;

  const MatchesResponse({
    this.competition,
    required this.matches,
  });

  factory MatchesResponse.fromJson(Map<String, dynamic> json) =>
      MatchesResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        matches: (json['matches'] as List)
            .map((e) => Match.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'competition': competition?.toJson(),
        'matches': matches.map((e) => e.toJson()).toList(),
      };
}

class Message {
  final String id;
  final String leagueId;
  final String? matchId;
  final String? parentId;
  final String? threadId;
  final String? userId;
  final double epoch;
  final String ciphertext;
  final String createdAt;
  final String? editedAt;
  final List<Attachment> attachments;

  /// One of: VISIBLE, PENDING, REMOVED.
  final String moderation;
  final bool reported;
  final Total reactions;

  /// One of: FIRE, GOAL, WOW, LAUGH, SAD, ANGRY.
  final String? myReaction;
  final double threadCount;

  const Message({
    required this.id,
    required this.leagueId,
    this.matchId,
    this.parentId,
    this.threadId,
    this.userId,
    required this.epoch,
    required this.ciphertext,
    required this.createdAt,
    this.editedAt,
    required this.attachments,
    required this.moderation,
    required this.reported,
    required this.reactions,
    this.myReaction,
    required this.threadCount,
  });

  factory Message.fromJson(Map<String, dynamic> json) => Message(
        id: json['id'] as String,
        leagueId: json['leagueId'] as String,
        matchId: json['matchId'] as String?,
        parentId: json['parentId'] as String?,
        threadId: json['threadId'] as String?,
        userId: json['userId'] as String?,
        epoch: (json['epoch'] as num).toDouble(),
        ciphertext: json['ciphertext'] as String,
        createdAt: json['createdAt'] as String,
        editedAt: json['editedAt'] as String?,
        attachments: (json['attachments'] as List)
            .map((e) => Attachment.fromJson(e as Map<String, dynamic>))
            .toList(),
        moderation: json['moderation'] as String,
        reported: json['reported'] as bool,
        reactions: Total.fromJson(json['reactions'] as Map<String, dynamic>),
        myReaction: json['myReaction'] as String?,
        threadCount: (json['threadCount'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'leagueId': leagueId,
        'matchId': matchId,
        'parentId': parentId,
        'threadId': threadId,
        'userId': userId,
        'epoch': epoch,
        'ciphertext': ciphertext,
        'createdAt': createdAt,
        'editedAt': editedAt,
        'attachments': attachments.map((e) => e.toJson()).toList(),
        'moderation': moderation,
        'reported': reported,
        'reactions': reactions.toJson(),
        'myReaction': myReaction,
        'threadCount': threadCount,
      };
}

class MissingKey {
  final String userId;
  final String publicKey;
  final String name;

  const MissingKey({
    required this.userId,
    required this.publicKey,
    required this.name,
  });

  factory MissingKey.fromJson(Map<String, dynamic> json) => MissingKey(
        userId: json['userId'] as String,
        publicKey: json['publicKey'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'userId': userId,
        'publicKey': publicKey,
        'name': name,
      };
}

class ModeBoardResponse {
  final Board board;

  /// One of: NORMAL, EASY, HARD, HARDCORE.
  final String mode;
  final double? lives;

  const ModeBoardResponse({
    required this.board,
    required this.mode,
    this.lives,
  });

  factory ModeBoardResponse.fromJson(Map<String, dynamic> json) =>
      ModeBoardResponse(
        board: Board.fromJson(json['board'] as Map<String, dynamic>),
        mode: json['mode'] as String,
        lives: (json['lives'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'board': board.toJson(),
        'mode': mode,
        'lives': lives,
      };
}

class MyPick {
  final String id;
  final String userId;
  final String competitionId;
  final String? teamCode;
  final String teamName;
  final int? fifaRank;
  final int potentialPoints;
  final int awardedPoints;
  final bool repicked;
  final String? originalTeamCode;
  final String? originalTeamName;
  final DateTime createdAt;
  final DateTime updatedAt;

  const MyPick({
    required this.id,
    required this.userId,
    required this.competitionId,
    this.teamCode,
    required this.teamName,
    this.fifaRank,
    required this.potentialPoints,
    required this.awardedPoints,
    required this.repicked,
    this.originalTeamCode,
    this.originalTeamName,
    required this.createdAt,
    required this.updatedAt,
  });

  factory MyPick.fromJson(Map<String, dynamic> json) => MyPick(
        id: json['id'] as String,
        userId: json['userId'] as String,
        competitionId: json['competitionId'] as String,
        teamCode: json['teamCode'] as String?,
        teamName: json['teamName'] as String,
        fifaRank: json['fifaRank'] as int?,
        potentialPoints: json['potentialPoints'] as int,
        awardedPoints: json['awardedPoints'] as int,
        repicked: json['repicked'] as bool,
        originalTeamCode: json['originalTeamCode'] as String?,
        originalTeamName: json['originalTeamName'] as String?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        updatedAt: DateTime.parse(json['updatedAt'] as String),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'competitionId': competitionId,
        'teamCode': teamCode,
        'teamName': teamName,
        'fifaRank': fifaRank,
        'potentialPoints': potentialPoints,
        'awardedPoints': awardedPoints,
        'repicked': repicked,
        'originalTeamCode': originalTeamCode,
        'originalTeamName': originalTeamName,
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
      };
}

class MyPick2 {
  final String id;
  final String userId;
  final String competitionId;
  final String playerId;
  final String playerName;
  final String? teamCode;
  final String teamName;
  final int awardedPoints;
  final bool repicked;
  final String? originalPlayerName;
  final String? originalTeamCode;
  final DateTime createdAt;
  final DateTime updatedAt;

  const MyPick2({
    required this.id,
    required this.userId,
    required this.competitionId,
    required this.playerId,
    required this.playerName,
    this.teamCode,
    required this.teamName,
    required this.awardedPoints,
    required this.repicked,
    this.originalPlayerName,
    this.originalTeamCode,
    required this.createdAt,
    required this.updatedAt,
  });

  factory MyPick2.fromJson(Map<String, dynamic> json) => MyPick2(
        id: json['id'] as String,
        userId: json['userId'] as String,
        competitionId: json['competitionId'] as String,
        playerId: json['playerId'] as String,
        playerName: json['playerName'] as String,
        teamCode: json['teamCode'] as String?,
        teamName: json['teamName'] as String,
        awardedPoints: json['awardedPoints'] as int,
        repicked: json['repicked'] as bool,
        originalPlayerName: json['originalPlayerName'] as String?,
        originalTeamCode: json['originalTeamCode'] as String?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        updatedAt: DateTime.parse(json['updatedAt'] as String),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'competitionId': competitionId,
        'playerId': playerId,
        'playerName': playerName,
        'teamCode': teamCode,
        'teamName': teamName,
        'awardedPoints': awardedPoints,
        'repicked': repicked,
        'originalPlayerName': originalPlayerName,
        'originalTeamCode': originalTeamCode,
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
      };
}

class MyPrediction {
  final String id;
  final String userId;
  final String matchId;
  final String roundId;
  final int homeGoals;
  final int awayGoals;
  final bool isOutcomeOnly;
  final int? wager;
  final bool isJoker;
  final DateTime? lockedAt;
  final int? basePoints;

  /// One of: EXACT, DIFF, OUTCOME, MISS.
  final String? baseTier;
  final int? bonusPoints;

  /// One of: NONE, CROWD, ODDS.
  final String? bonusSource;
  final String? crowdShare;
  final String? jokerMultiplierApplied;
  final int? totalPoints;
  final int? scoredAtVersion;
  final DateTime? scoredAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  const MyPrediction({
    required this.id,
    required this.userId,
    required this.matchId,
    required this.roundId,
    required this.homeGoals,
    required this.awayGoals,
    required this.isOutcomeOnly,
    this.wager,
    required this.isJoker,
    this.lockedAt,
    this.basePoints,
    this.baseTier,
    this.bonusPoints,
    this.bonusSource,
    this.crowdShare,
    this.jokerMultiplierApplied,
    this.totalPoints,
    this.scoredAtVersion,
    this.scoredAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory MyPrediction.fromJson(Map<String, dynamic> json) => MyPrediction(
        id: json['id'] as String,
        userId: json['userId'] as String,
        matchId: json['matchId'] as String,
        roundId: json['roundId'] as String,
        homeGoals: json['homeGoals'] as int,
        awayGoals: json['awayGoals'] as int,
        isOutcomeOnly: json['isOutcomeOnly'] as bool,
        wager: json['wager'] as int?,
        isJoker: json['isJoker'] as bool,
        lockedAt: json['lockedAt'] == null
            ? null
            : DateTime.parse(json['lockedAt'] as String),
        basePoints: json['basePoints'] as int?,
        baseTier: json['baseTier'] as String?,
        bonusPoints: json['bonusPoints'] as int?,
        bonusSource: json['bonusSource'] as String?,
        crowdShare: json['crowdShare'] as String?,
        jokerMultiplierApplied: json['jokerMultiplierApplied'] as String?,
        totalPoints: json['totalPoints'] as int?,
        scoredAtVersion: json['scoredAtVersion'] as int?,
        scoredAt: json['scoredAt'] == null
            ? null
            : DateTime.parse(json['scoredAt'] as String),
        createdAt: DateTime.parse(json['createdAt'] as String),
        updatedAt: DateTime.parse(json['updatedAt'] as String),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'matchId': matchId,
        'roundId': roundId,
        'homeGoals': homeGoals,
        'awayGoals': awayGoals,
        'isOutcomeOnly': isOutcomeOnly,
        'wager': wager,
        'isJoker': isJoker,
        'lockedAt': lockedAt?.toIso8601String(),
        'basePoints': basePoints,
        'baseTier': baseTier,
        'bonusPoints': bonusPoints,
        'bonusSource': bonusSource,
        'crowdShare': crowdShare,
        'jokerMultiplierApplied': jokerMultiplierApplied,
        'totalPoints': totalPoints,
        'scoredAtVersion': scoredAtVersion,
        'scoredAt': scoredAt?.toIso8601String(),
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
      };
}

class MyWrappedKey {
  final double epoch;
  final String wrappedKey;

  const MyWrappedKey({
    required this.epoch,
    required this.wrappedKey,
  });

  factory MyWrappedKey.fromJson(Map<String, dynamic> json) => MyWrappedKey(
        epoch: (json['epoch'] as num).toDouble(),
        wrappedKey: json['wrappedKey'] as String,
      );

  Map<String, dynamic> toJson() => {
        'epoch': epoch,
        'wrappedKey': wrappedKey,
      };
}

class NotificationData {
  final String id;

  /// One of: LEAGUE_JOIN, LEAGUE_ROLE, LEAGUE_REMOVED, PICK_REMINDER, MATCH_RESULT, CHAMPION_RESULT, BEST_SCORER_RESULT, TROPHY_AWARDED, ACHIEVEMENT_UNLOCKED, CHAT_MENTION, DM_MESSAGE, VOICE_MISSED.
  final String type;
  final Map<String, dynamic> data;
  final bool read;
  final String createdAt;

  const NotificationData({
    required this.id,
    required this.type,
    required this.data,
    required this.read,
    required this.createdAt,
  });

  factory NotificationData.fromJson(Map<String, dynamic> json) =>
      NotificationData(
        id: json['id'] as String,
        type: json['type'] as String,
        data: (json['data'] as Map<String, dynamic>).cast(),
        read: json['read'] as bool,
        createdAt: json['createdAt'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'type': type,
        'data': data,
        'read': read,
        'createdAt': createdAt,
      };
}

class NotificationsResponse {
  final List<NotificationData> notifications;
  final double unreadCount;

  const NotificationsResponse({
    required this.notifications,
    required this.unreadCount,
  });

  factory NotificationsResponse.fromJson(Map<String, dynamic> json) =>
      NotificationsResponse(
        notifications: (json['notifications'] as List)
            .map((e) => NotificationData.fromJson(e as Map<String, dynamic>))
            .toList(),
        unreadCount: (json['unreadCount'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'notifications': notifications.map((e) => e.toJson()).toList(),
        'unreadCount': unreadCount,
      };
}

class Odd {
  final double home;
  final double draw;
  final double away;
  final DateTime fetchedAt;
  final Initial? initial;
  final List<Bookmaker>? bookmakers;

  const Odd({
    required this.home,
    required this.draw,
    required this.away,
    required this.fetchedAt,
    this.initial,
    this.bookmakers,
  });

  factory Odd.fromJson(Map<String, dynamic> json) => Odd(
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
        fetchedAt: DateTime.parse(json['fetchedAt'] as String),
        initial: json['initial'] == null
            ? null
            : Initial.fromJson(json['initial'] as Map<String, dynamic>),
        bookmakers: json['bookmakers'] == null
            ? null
            : (json['bookmakers'] as List)
                .map((e) => Bookmaker.fromJson(e as Map<String, dynamic>))
                .toList(),
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'draw': draw,
        'away': away,
        'fetchedAt': fetchedAt.toIso8601String(),
        'initial': initial?.toJson(),
        'bookmakers': bookmakers?.map((e) => e.toJson()).toList(),
      };
}

class Other {
  final String id;
  final String name;
  final String? image;

  const Other({
    required this.id,
    required this.name,
    this.image,
  });

  factory Other.fromJson(Map<String, dynamic> json) => Other(
        id: json['id'] as String,
        name: json['name'] as String,
        image: json['image'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'image': image,
      };
}

class Other2 {
  final String userId;
  final String name;
  final String? image;
  final String publicKey;

  const Other2({
    required this.userId,
    required this.name,
    this.image,
    required this.publicKey,
  });

  factory Other2.fromJson(Map<String, dynamic> json) => Other2(
        userId: json['userId'] as String,
        name: json['name'] as String,
        image: json['image'] as String?,
        publicKey: json['publicKey'] as String,
      );

  Map<String, dynamic> toJson() => {
        'userId': userId,
        'name': name,
        'image': image,
        'publicKey': publicKey,
      };
}

class OutcomeLean {
  final Predicted predicted;
  final Predicted actual;
  final double homeBiasPct;
  final double drawGapPct;

  const OutcomeLean({
    required this.predicted,
    required this.actual,
    required this.homeBiasPct,
    required this.drawGapPct,
  });

  factory OutcomeLean.fromJson(Map<String, dynamic> json) => OutcomeLean(
        predicted:
            Predicted.fromJson(json['predicted'] as Map<String, dynamic>),
        actual: Predicted.fromJson(json['actual'] as Map<String, dynamic>),
        homeBiasPct: (json['homeBiasPct'] as num).toDouble(),
        drawGapPct: (json['drawGapPct'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'predicted': predicted.toJson(),
        'actual': actual.toJson(),
        'homeBiasPct': homeBiasPct,
        'drawGapPct': drawGapPct,
      };
}

class OverTime {
  final String label;
  final double order;
  final double picks;
  final double accuracy;
  final double points;

  const OverTime({
    required this.label,
    required this.order,
    required this.picks,
    required this.accuracy,
    required this.points,
  });

  factory OverTime.fromJson(Map<String, dynamic> json) => OverTime(
        label: json['label'] as String,
        order: (json['order'] as num).toDouble(),
        picks: (json['picks'] as num).toDouble(),
        accuracy: (json['accuracy'] as num).toDouble(),
        points: (json['points'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'label': label,
        'order': order,
        'picks': picks,
        'accuracy': accuracy,
        'points': points,
      };
}

class Overrated {
  final String? code;
  final String name;
  final double sample;
  final double predictedWinRate;
  final double actualWinRate;
  final double delta;

  const Overrated({
    this.code,
    required this.name,
    required this.sample,
    required this.predictedWinRate,
    required this.actualWinRate,
    required this.delta,
  });

  factory Overrated.fromJson(Map<String, dynamic> json) => Overrated(
        code: json['code'] as String?,
        name: json['name'] as String,
        sample: (json['sample'] as num).toDouble(),
        predictedWinRate: (json['predictedWinRate'] as num).toDouble(),
        actualWinRate: (json['actualWinRate'] as num).toDouble(),
        delta: (json['delta'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'code': code,
        'name': name,
        'sample': sample,
        'predictedWinRate': predictedWinRate,
        'actualWinRate': actualWinRate,
        'delta': delta,
      };
}

class PastPicksResponse {
  /// One of: none, live, final.
  final String scope;
  final Earlier? earlier;
  final Earlier? kept;
  final bool? cheeky;

  const PastPicksResponse({
    required this.scope,
    this.earlier,
    this.kept,
    this.cheeky,
  });

  factory PastPicksResponse.fromJson(Map<String, dynamic> json) =>
      PastPicksResponse(
        scope: json['scope'] as String,
        earlier: json['earlier'] == null
            ? null
            : Earlier.fromJson(json['earlier'] as Map<String, dynamic>),
        kept: json['kept'] == null
            ? null
            : Earlier.fromJson(json['kept'] as Map<String, dynamic>),
        cheeky: json['cheeky'] as bool?,
      );

  Map<String, dynamic> toJson() => {
        'scope': scope,
        'earlier': earlier?.toJson(),
        'kept': kept?.toJson(),
        'cheeky': cheeky,
      };
}

class Predicted {
  final double home;
  final double draw;
  final double away;

  const Predicted({
    required this.home,
    required this.draw,
    required this.away,
  });

  factory Predicted.fromJson(Map<String, dynamic> json) => Predicted(
        home: (json['home'] as num).toDouble(),
        draw: (json['draw'] as num).toDouble(),
        away: (json['away'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'draw': draw,
        'away': away,
      };
}

class Prediction {
  final String id;
  final String userId;
  final String matchId;
  final String roundId;
  final int homeGoals;
  final int awayGoals;
  final bool isOutcomeOnly;
  final int? wager;
  final bool isJoker;

  /// One of: EXACT, DIFF, OUTCOME, MISS.
  final String? baseTier;
  final int? totalPoints;
  final int? basePoints;
  final int? bonusPoints;
  final String? crowdShare;
  final String? jokerMultiplierApplied;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;

  /// One of: SCHEDULED, LIVE, PAUSED, FINISHED, POSTPONED, CANCELLED, SUSPENDED, AWARDED, INTERRUPTED.
  final String status;

  /// One of: GROUP, R32, R16, QF, SF, THIRD_PLACE, FINAL.
  final String stage;
  final int? fullTimeHome;
  final int? fullTimeAway;
  final int? penaltiesHome;
  final int? penaltiesAway;
  final String roundLabel;
  final int roundSort;

  const Prediction({
    required this.id,
    required this.userId,
    required this.matchId,
    required this.roundId,
    required this.homeGoals,
    required this.awayGoals,
    required this.isOutcomeOnly,
    this.wager,
    required this.isJoker,
    this.baseTier,
    this.totalPoints,
    this.basePoints,
    this.bonusPoints,
    this.crowdShare,
    this.jokerMultiplierApplied,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    required this.stage,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    required this.roundLabel,
    required this.roundSort,
  });

  factory Prediction.fromJson(Map<String, dynamic> json) => Prediction(
        id: json['id'] as String,
        userId: json['userId'] as String,
        matchId: json['matchId'] as String,
        roundId: json['roundId'] as String,
        homeGoals: json['homeGoals'] as int,
        awayGoals: json['awayGoals'] as int,
        isOutcomeOnly: json['isOutcomeOnly'] as bool,
        wager: json['wager'] as int?,
        isJoker: json['isJoker'] as bool,
        baseTier: json['baseTier'] as String?,
        totalPoints: json['totalPoints'] as int?,
        basePoints: json['basePoints'] as int?,
        bonusPoints: json['bonusPoints'] as int?,
        crowdShare: json['crowdShare'] as String?,
        jokerMultiplierApplied: json['jokerMultiplierApplied'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        stage: json['stage'] as String,
        fullTimeHome: json['fullTimeHome'] as int?,
        fullTimeAway: json['fullTimeAway'] as int?,
        penaltiesHome: json['penaltiesHome'] as int?,
        penaltiesAway: json['penaltiesAway'] as int?,
        roundLabel: json['roundLabel'] as String,
        roundSort: json['roundSort'] as int,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'matchId': matchId,
        'roundId': roundId,
        'homeGoals': homeGoals,
        'awayGoals': awayGoals,
        'isOutcomeOnly': isOutcomeOnly,
        'wager': wager,
        'isJoker': isJoker,
        'baseTier': baseTier,
        'totalPoints': totalPoints,
        'basePoints': basePoints,
        'bonusPoints': bonusPoints,
        'crowdShare': crowdShare,
        'jokerMultiplierApplied': jokerMultiplierApplied,
        'homeTeam': homeTeam,
        'awayTeam': awayTeam,
        'homeTeamCode': homeTeamCode,
        'awayTeamCode': awayTeamCode,
        'kickoffTime': kickoffTime.toIso8601String(),
        'status': status,
        'stage': stage,
        'fullTimeHome': fullTimeHome,
        'fullTimeAway': fullTimeAway,
        'penaltiesHome': penaltiesHome,
        'penaltiesAway': penaltiesAway,
        'roundLabel': roundLabel,
        'roundSort': roundSort,
      };
}

class Prediction2 {
  final String id;
  final String userId;
  final String matchId;
  final String roundId;
  final double homeGoals;
  final double awayGoals;
  final bool isOutcomeOnly;
  final double? wager;
  final bool isJoker;
  final String? baseTier;
  final double? totalPoints;
  final double? basePoints;
  final double? bonusPoints;
  final String? crowdShare;
  final String? jokerMultiplierApplied;
  final String homeTeam;
  final String awayTeam;
  final String? homeTeamCode;
  final String? awayTeamCode;
  final DateTime kickoffTime;
  final String status;
  final String stage;
  final double? fullTimeHome;
  final double? fullTimeAway;
  final double? penaltiesHome;
  final double? penaltiesAway;
  final String roundLabel;
  final double roundSort;
  final double consensusCount;
  final double consensusTotal;

  /// One of: MODE, MEAN.
  final String consensusMethod;

  const Prediction2({
    required this.id,
    required this.userId,
    required this.matchId,
    required this.roundId,
    required this.homeGoals,
    required this.awayGoals,
    required this.isOutcomeOnly,
    this.wager,
    required this.isJoker,
    this.baseTier,
    this.totalPoints,
    this.basePoints,
    this.bonusPoints,
    this.crowdShare,
    this.jokerMultiplierApplied,
    required this.homeTeam,
    required this.awayTeam,
    this.homeTeamCode,
    this.awayTeamCode,
    required this.kickoffTime,
    required this.status,
    required this.stage,
    this.fullTimeHome,
    this.fullTimeAway,
    this.penaltiesHome,
    this.penaltiesAway,
    required this.roundLabel,
    required this.roundSort,
    required this.consensusCount,
    required this.consensusTotal,
    required this.consensusMethod,
  });

  factory Prediction2.fromJson(Map<String, dynamic> json) => Prediction2(
        id: json['id'] as String,
        userId: json['userId'] as String,
        matchId: json['matchId'] as String,
        roundId: json['roundId'] as String,
        homeGoals: (json['homeGoals'] as num).toDouble(),
        awayGoals: (json['awayGoals'] as num).toDouble(),
        isOutcomeOnly: json['isOutcomeOnly'] as bool,
        wager: (json['wager'] as num?)?.toDouble(),
        isJoker: json['isJoker'] as bool,
        baseTier: json['baseTier'] as String?,
        totalPoints: (json['totalPoints'] as num?)?.toDouble(),
        basePoints: (json['basePoints'] as num?)?.toDouble(),
        bonusPoints: (json['bonusPoints'] as num?)?.toDouble(),
        crowdShare: json['crowdShare'] as String?,
        jokerMultiplierApplied: json['jokerMultiplierApplied'] as String?,
        homeTeam: json['homeTeam'] as String,
        awayTeam: json['awayTeam'] as String,
        homeTeamCode: json['homeTeamCode'] as String?,
        awayTeamCode: json['awayTeamCode'] as String?,
        kickoffTime: DateTime.parse(json['kickoffTime'] as String),
        status: json['status'] as String,
        stage: json['stage'] as String,
        fullTimeHome: (json['fullTimeHome'] as num?)?.toDouble(),
        fullTimeAway: (json['fullTimeAway'] as num?)?.toDouble(),
        penaltiesHome: (json['penaltiesHome'] as num?)?.toDouble(),
        penaltiesAway: (json['penaltiesAway'] as num?)?.toDouble(),
        roundLabel: json['roundLabel'] as String,
        roundSort: (json['roundSort'] as num).toDouble(),
        consensusCount: (json['consensusCount'] as num).toDouble(),
        consensusTotal: (json['consensusTotal'] as num).toDouble(),
        consensusMethod: json['consensusMethod'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'matchId': matchId,
        'roundId': roundId,
        'homeGoals': homeGoals,
        'awayGoals': awayGoals,
        'isOutcomeOnly': isOutcomeOnly,
        'wager': wager,
        'isJoker': isJoker,
        'baseTier': baseTier,
        'totalPoints': totalPoints,
        'basePoints': basePoints,
        'bonusPoints': bonusPoints,
        'crowdShare': crowdShare,
        'jokerMultiplierApplied': jokerMultiplierApplied,
        'homeTeam': homeTeam,
        'awayTeam': awayTeam,
        'homeTeamCode': homeTeamCode,
        'awayTeamCode': awayTeamCode,
        'kickoffTime': kickoffTime.toIso8601String(),
        'status': status,
        'stage': stage,
        'fullTimeHome': fullTimeHome,
        'fullTimeAway': fullTimeAway,
        'penaltiesHome': penaltiesHome,
        'penaltiesAway': penaltiesAway,
        'roundLabel': roundLabel,
        'roundSort': roundSort,
        'consensusCount': consensusCount,
        'consensusTotal': consensusTotal,
        'consensusMethod': consensusMethod,
      };
}

class PredictionInput {
  final int home;
  final int away;
  final bool? isOutcomeOnly;
  final int? wager;

  const PredictionInput({
    required this.home,
    required this.away,
    this.isOutcomeOnly,
    this.wager,
  });

  factory PredictionInput.fromJson(Map<String, dynamic> json) =>
      PredictionInput(
        home: json['home'] as int,
        away: json['away'] as int,
        isOutcomeOnly: json['isOutcomeOnly'] as bool?,
        wager: json['wager'] as int?,
      );

  Map<String, dynamic> toJson() => {
        'home': home,
        'away': away,
        'isOutcomeOnly': isOutcomeOnly,
        'wager': wager,
      };
}

class PredictionSaveResponse {
  final String id;

  const PredictionSaveResponse({
    required this.id,
  });

  factory PredictionSaveResponse.fromJson(Map<String, dynamic> json) =>
      PredictionSaveResponse(
        id: json['id'] as String,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
      };
}

class PredictionsResponse {
  final List<Prediction> predictions;

  const PredictionsResponse({
    required this.predictions,
  });

  factory PredictionsResponse.fromJson(Map<String, dynamic> json) =>
      PredictionsResponse(
        predictions: (json['predictions'] as List)
            .map((e) => Prediction.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'predictions': predictions.map((e) => e.toJson()).toList(),
      };
}

class PublicLeaguesResponse {
  final Competition2? competition;
  final List<League3> leagues;

  const PublicLeaguesResponse({
    this.competition,
    required this.leagues,
  });

  factory PublicLeaguesResponse.fromJson(Map<String, dynamic> json) =>
      PublicLeaguesResponse(
        competition: json['competition'] == null
            ? null
            : Competition2.fromJson(
                json['competition'] as Map<String, dynamic>),
        leagues: (json['leagues'] as List)
            .map((e) => League3.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'competition': competition?.toJson(),
        'leagues': leagues.map((e) => e.toJson()).toList(),
      };
}

class ReactionsResponse {
  final Total totals;

  /// One of: FIRE, GOAL, WOW, LAUGH, SAD, ANGRY.
  final String? mine;

  const ReactionsResponse({
    required this.totals,
    this.mine,
  });

  factory ReactionsResponse.fromJson(Map<String, dynamic> json) =>
      ReactionsResponse(
        totals: Total.fromJson(json['totals'] as Map<String, dynamic>),
        mine: json['mine'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'totals': totals.toJson(),
        'mine': mine,
      };
}

class Recipient {
  final String userId;
  final String name;
  final String? image;
  final bool shared;

  const Recipient({
    required this.userId,
    required this.name,
    this.image,
    required this.shared,
  });

  factory Recipient.fromJson(Map<String, dynamic> json) => Recipient(
        userId: json['userId'] as String,
        name: json['name'] as String,
        image: json['image'] as String?,
        shared: json['shared'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'userId': userId,
        'name': name,
        'image': image,
        'shared': shared,
      };
}

class RoadmapResponse {
  final List<Item> items;

  const RoadmapResponse({
    required this.items,
  });

  factory RoadmapResponse.fromJson(Map<String, dynamic> json) =>
      RoadmapResponse(
        items: (json['items'] as List)
            .map((e) => Item.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'items': items.map((e) => e.toJson()).toList(),
      };
}

class RowData {
  final String? code;
  final String name;
  final double played;
  final double won;
  final double drawn;
  final double lost;
  final double gf;
  final double ga;
  final double gd;
  final double points;

  const RowData({
    this.code,
    required this.name,
    required this.played,
    required this.won,
    required this.drawn,
    required this.lost,
    required this.gf,
    required this.ga,
    required this.gd,
    required this.points,
  });

  factory RowData.fromJson(Map<String, dynamic> json) => RowData(
        code: json['code'] as String?,
        name: json['name'] as String,
        played: (json['played'] as num).toDouble(),
        won: (json['won'] as num).toDouble(),
        drawn: (json['drawn'] as num).toDouble(),
        lost: (json['lost'] as num).toDouble(),
        gf: (json['gf'] as num).toDouble(),
        ga: (json['ga'] as num).toDouble(),
        gd: (json['gd'] as num).toDouble(),
        points: (json['points'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'code': code,
        'name': name,
        'played': played,
        'won': won,
        'drawn': drawn,
        'lost': lost,
        'gf': gf,
        'ga': ga,
        'gd': gd,
        'points': points,
      };
}

class RowData2 {
  final double rank;
  final String userId;
  final String displayName;
  final String? image;
  final double totalPoints;
  final double predictionPoints;
  final double championPoints;
  final String? championCode;
  final String? championName;
  final double bestScorerPoints;
  final String? bestScorerName;
  final String? bestScorerCode;
  final double livePoints;
  final double exactCount;
  final double outcomeCount;
  final double gdCount;
  final List<Showcase> showcase;
  final double? movement;

  const RowData2({
    required this.rank,
    required this.userId,
    required this.displayName,
    this.image,
    required this.totalPoints,
    required this.predictionPoints,
    required this.championPoints,
    this.championCode,
    this.championName,
    required this.bestScorerPoints,
    this.bestScorerName,
    this.bestScorerCode,
    required this.livePoints,
    required this.exactCount,
    required this.outcomeCount,
    required this.gdCount,
    required this.showcase,
    this.movement,
  });

  factory RowData2.fromJson(Map<String, dynamic> json) => RowData2(
        rank: (json['rank'] as num).toDouble(),
        userId: json['userId'] as String,
        displayName: json['displayName'] as String,
        image: json['image'] as String?,
        totalPoints: (json['totalPoints'] as num).toDouble(),
        predictionPoints: (json['predictionPoints'] as num).toDouble(),
        championPoints: (json['championPoints'] as num).toDouble(),
        championCode: json['championCode'] as String?,
        championName: json['championName'] as String?,
        bestScorerPoints: (json['bestScorerPoints'] as num).toDouble(),
        bestScorerName: json['bestScorerName'] as String?,
        bestScorerCode: json['bestScorerCode'] as String?,
        livePoints: (json['livePoints'] as num).toDouble(),
        exactCount: (json['exactCount'] as num).toDouble(),
        outcomeCount: (json['outcomeCount'] as num).toDouble(),
        gdCount: (json['gdCount'] as num).toDouble(),
        showcase: (json['showcase'] as List)
            .map((e) => Showcase.fromJson(e as Map<String, dynamic>))
            .toList(),
        movement: (json['movement'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'rank': rank,
        'userId': userId,
        'displayName': displayName,
        'image': image,
        'totalPoints': totalPoints,
        'predictionPoints': predictionPoints,
        'championPoints': championPoints,
        'championCode': championCode,
        'championName': championName,
        'bestScorerPoints': bestScorerPoints,
        'bestScorerName': bestScorerName,
        'bestScorerCode': bestScorerCode,
        'livePoints': livePoints,
        'exactCount': exactCount,
        'outcomeCount': outcomeCount,
        'gdCount': gdCount,
        'showcase': showcase.map((e) => e.toJson()).toList(),
        'movement': movement,
      };
}

class Scorer {
  final String playerName;
  final String teamName;
  final String? teamCode;
  final double goals;
  final double? assists;
  final double? penalties;

  const Scorer({
    required this.playerName,
    required this.teamName,
    this.teamCode,
    required this.goals,
    this.assists,
    this.penalties,
  });

  factory Scorer.fromJson(Map<String, dynamic> json) => Scorer(
        playerName: json['playerName'] as String,
        teamName: json['teamName'] as String,
        teamCode: json['teamCode'] as String?,
        goals: (json['goals'] as num).toDouble(),
        assists: (json['assists'] as num?)?.toDouble(),
        penalties: (json['penalties'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'playerName': playerName,
        'teamName': teamName,
        'teamCode': teamCode,
        'goals': goals,
        'assists': assists,
        'penalties': penalties,
      };
}

class ScorersResponse {
  final List<Scorer> scorers;
  final List<Scorer> assists;

  const ScorersResponse({
    required this.scorers,
    required this.assists,
  });

  factory ScorersResponse.fromJson(Map<String, dynamic> json) =>
      ScorersResponse(
        scorers: (json['scorers'] as List)
            .map((e) => Scorer.fromJson(e as Map<String, dynamic>))
            .toList(),
        assists: (json['assists'] as List)
            .map((e) => Scorer.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'scorers': scorers.map((e) => e.toJson()).toList(),
        'assists': assists.map((e) => e.toJson()).toList(),
      };
}

class SecondChance {
  final bool open;
  final String? closesAt;

  const SecondChance({
    required this.open,
    this.closesAt,
  });

  factory SecondChance.fromJson(Map<String, dynamic> json) => SecondChance(
        open: json['open'] as bool,
        closesAt: json['closesAt'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'open': open,
        'closesAt': closesAt,
      };
}

class Showcase {
  final String key;
  final String category;

  /// One of: BRONZE, SILVER, GOLD, DIAMOND.
  final String? tier;

  const Showcase({
    required this.key,
    required this.category,
    this.tier,
  });

  factory Showcase.fromJson(Map<String, dynamic> json) => Showcase(
        key: json['key'] as String,
        category: json['category'] as String,
        tier: json['tier'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'key': key,
        'category': category,
        'tier': tier,
      };
}

class StandingsResponse {
  final List<Group> groups;

  const StandingsResponse({
    required this.groups,
  });

  factory StandingsResponse.fromJson(Map<String, dynamic> json) =>
      StandingsResponse(
        groups: (json['groups'] as List)
            .map((e) => Group.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'groups': groups.map((e) => e.toJson()).toList(),
      };
}

class Streak {
  final double current;
  final double best;

  const Streak({
    required this.current,
    required this.best,
  });

  factory Streak.fromJson(Map<String, dynamic> json) => Streak(
        current: (json['current'] as num).toDouble(),
        best: (json['best'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'current': current,
        'best': best,
      };
}

class Subject {
  final double rank;
  final double totalPoints;
  final double exactCount;
  final double outcomeCount;

  const Subject({
    required this.rank,
    required this.totalPoints,
    required this.exactCount,
    required this.outcomeCount,
  });

  factory Subject.fromJson(Map<String, dynamic> json) => Subject(
        rank: (json['rank'] as num).toDouble(),
        totalPoints: (json['totalPoints'] as num).toDouble(),
        exactCount: (json['exactCount'] as num).toDouble(),
        outcomeCount: (json['outcomeCount'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'rank': rank,
        'totalPoints': totalPoints,
        'exactCount': exactCount,
        'outcomeCount': outcomeCount,
      };
}

class Summary {
  final double? rank;
  final double totalPoints;
  final double predictionPoints;
  final double championPoints;
  final double exactCount;
  final double outcomeCount;
  final double gdCount;

  const Summary({
    this.rank,
    required this.totalPoints,
    required this.predictionPoints,
    required this.championPoints,
    required this.exactCount,
    required this.outcomeCount,
    required this.gdCount,
  });

  factory Summary.fromJson(Map<String, dynamic> json) => Summary(
        rank: (json['rank'] as num?)?.toDouble(),
        totalPoints: (json['totalPoints'] as num).toDouble(),
        predictionPoints: (json['predictionPoints'] as num).toDouble(),
        championPoints: (json['championPoints'] as num).toDouble(),
        exactCount: (json['exactCount'] as num).toDouble(),
        outcomeCount: (json['outcomeCount'] as num).toDouble(),
        gdCount: (json['gdCount'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'rank': rank,
        'totalPoints': totalPoints,
        'predictionPoints': predictionPoints,
        'championPoints': championPoints,
        'exactCount': exactCount,
        'outcomeCount': outcomeCount,
        'gdCount': gdCount,
      };
}

class Team {
  final List<Overrated> overrated;
  final List<Overrated> underrated;

  const Team({
    required this.overrated,
    required this.underrated,
  });

  factory Team.fromJson(Map<String, dynamic> json) => Team(
        overrated: (json['overrated'] as List)
            .map((e) => Overrated.fromJson(e as Map<String, dynamic>))
            .toList(),
        underrated: (json['underrated'] as List)
            .map((e) => Overrated.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'overrated': overrated.map((e) => e.toJson()).toList(),
        'underrated': underrated.map((e) => e.toJson()).toList(),
      };
}

class Team2 {
  final String code;
  final String name;
  final double? fifaRank;
  final double potentialPoints;

  const Team2({
    required this.code,
    required this.name,
    this.fifaRank,
    required this.potentialPoints,
  });

  factory Team2.fromJson(Map<String, dynamic> json) => Team2(
        code: json['code'] as String,
        name: json['name'] as String,
        fifaRank: (json['fifaRank'] as num?)?.toDouble(),
        potentialPoints: (json['potentialPoints'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'code': code,
        'name': name,
        'fifaRank': fifaRank,
        'potentialPoints': potentialPoints,
      };
}

class Team3 {
  final String code;
  final String name;

  const Team3({
    required this.code,
    required this.name,
  });

  factory Team3.fromJson(Map<String, dynamic> json) => Team3(
        code: json['code'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'code': code,
        'name': name,
      };
}

class Thread {
  final String threadId;
  final Other other;
  final String? lastMessageAt;
  final double unread;
  final String? myWrappedKey;

  const Thread({
    required this.threadId,
    required this.other,
    this.lastMessageAt,
    required this.unread,
    this.myWrappedKey,
  });

  factory Thread.fromJson(Map<String, dynamic> json) => Thread(
        threadId: json['threadId'] as String,
        other: Other.fromJson(json['other'] as Map<String, dynamic>),
        lastMessageAt: json['lastMessageAt'] as String?,
        unread: (json['unread'] as num).toDouble(),
        myWrappedKey: json['myWrappedKey'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'threadId': threadId,
        'other': other.toJson(),
        'lastMessageAt': lastMessageAt,
        'unread': unread,
        'myWrappedKey': myWrappedKey,
      };
}

class Thread2 {
  final String threadId;
  final double epoch;
  final Other2 other;
  final List<MyWrappedKey> myWrappedKeys;
  final bool otherMissingCurrentKey;

  const Thread2({
    required this.threadId,
    required this.epoch,
    required this.other,
    required this.myWrappedKeys,
    required this.otherMissingCurrentKey,
  });

  factory Thread2.fromJson(Map<String, dynamic> json) => Thread2(
        threadId: json['threadId'] as String,
        epoch: (json['epoch'] as num).toDouble(),
        other: Other2.fromJson(json['other'] as Map<String, dynamic>),
        myWrappedKeys: (json['myWrappedKeys'] as List)
            .map((e) => MyWrappedKey.fromJson(e as Map<String, dynamic>))
            .toList(),
        otherMissingCurrentKey: json['otherMissingCurrentKey'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'threadId': threadId,
        'epoch': epoch,
        'other': other.toJson(),
        'myWrappedKeys': myWrappedKeys.map((e) => e.toJson()).toList(),
        'otherMissingCurrentKey': otherMissingCurrentKey,
      };
}

class Tier {
  final double exact;
  final double diff;
  final double outcome;
  final double miss;

  const Tier({
    required this.exact,
    required this.diff,
    required this.outcome,
    required this.miss,
  });

  factory Tier.fromJson(Map<String, dynamic> json) => Tier(
        exact: (json['exact'] as num).toDouble(),
        diff: (json['diff'] as num).toDouble(),
        outcome: (json['outcome'] as num).toDouble(),
        miss: (json['miss'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'exact': exact,
        'diff': diff,
        'outcome': outcome,
        'miss': miss,
      };
}

class Total {
  final double fire;
  final double goal;
  final double wow;
  final double laugh;
  final double sad;
  final double angry;

  const Total({
    required this.fire,
    required this.goal,
    required this.wow,
    required this.laugh,
    required this.sad,
    required this.angry,
  });

  factory Total.fromJson(Map<String, dynamic> json) => Total(
        fire: (json['FIRE'] as num).toDouble(),
        goal: (json['GOAL'] as num).toDouble(),
        wow: (json['WOW'] as num).toDouble(),
        laugh: (json['LAUGH'] as num).toDouble(),
        sad: (json['SAD'] as num).toDouble(),
        angry: (json['ANGRY'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'FIRE': fire,
        'GOAL': goal,
        'WOW': wow,
        'LAUGH': laugh,
        'SAD': sad,
        'ANGRY': angry,
      };
}

class TrustStatusResponse {
  final bool trusted;

  const TrustStatusResponse({
    required this.trusted,
  });

  factory TrustStatusResponse.fromJson(Map<String, dynamic> json) =>
      TrustStatusResponse(
        trusted: json['trusted'] as bool,
      );

  Map<String, dynamic> toJson() => {
        'trusted': trusted,
      };
}
