// Generates lib/api/models.gen.dart from the committed OpenAPI snapshot
// (shared/contracts-openapi/openapi.snapshot.json). The snapshot inlines every
// schema (zod-to-openapi, no components/$ref), so we walk each targeted
// operation's response/request schema and emit immutable Dart models, sharing a
// class whenever two shapes are structurally identical.
//
// Run via tool/gen_models.sh. The output is deterministic (classes sorted by
// name, fields in schema order) so CI can assert it is not stale with
// `git diff --exit-code lib/api/models.gen.dart`.

import 'dart:convert';
import 'dart:io';

/// The API surface the mobile client consumes. Extend as phases add endpoints.
const targets = <Target>[
  Target('get', '/api/competitions', 'CompetitionsResponse'),
  Target('get', '/api/competitions/standings', 'StandingsResponse'),
  Target('get', '/api/competitions/scorers', 'ScorersResponse'),
  Target('get', '/api/matches', 'MatchesResponse'),
  Target('get', '/api/matches/{id}', 'MatchDetailResponse'),
  Target('get', '/api/leaderboard', 'LeaderboardResponse'),
  Target('get', '/api/leagues', 'LeaguesResponse'),
  Target('get', '/api/predictions', 'PredictionsResponse'),
  Target('get', '/api/me/trust-status', 'TrustStatusResponse'),
  Target('put', '/api/leagues/{id}/predictions/{matchId}', 'PredictionSaveResponse',
      reqName: 'PredictionInput'),
  // Phase 2 - social + read-only
  Target('get', '/api/leagues/public', 'PublicLeaguesResponse'),
  Target('get', '/api/notifications', 'NotificationsResponse'),
  Target('get', '/api/me/analytics', 'AnalyticsResponse'),
  // /api/me/wrapped is a top-level oneOf (ready vs not-ready) - read raw, not typed.
  Target('get', '/api/reactions/{matchId}', 'ReactionsResponse'),
  Target('get', '/api/leagues/{id}/mode-board', 'ModeBoardResponse'),
];

class Target {
  final String method;
  final String path;
  final String resName;
  final String? reqName;
  const Target(this.method, this.path, this.resName, {this.reqName});
}

/// A resolved Dart field on a generated class.
class Field {
  final String jsonKey;
  final String dartName;
  final String type; // Dart type, e.g. `String`, `List<Team>`, `DateTime?`
  final bool nullable;
  final _Kind kind;
  final String? elementParse; // for lists/objects: how to build one element
  final List<String>? enumValues;
  Field(this.jsonKey, this.dartName, this.type, this.nullable, this.kind,
      {this.elementParse, this.enumValues});
}

enum _Kind { scalar, dateTime, object, listScalar, listDateTime, listObject, map, raw }

class ModelClass {
  final String name;
  final List<Field> fields;
  ModelClass(this.name, this.fields);
}

// signature -> emitted class name, so identical inline shapes collapse to one class.
final Map<String, String> _bySignature = {};
final Map<String, ModelClass> _classes = {};
final Set<String> _usedNames = {};

void main() {
  final root = _repoRoot();
  final snap = jsonDecode(
      File('$root/shared/contracts-openapi/openapi.snapshot.json').readAsStringSync())
      as Map<String, dynamic>;
  final paths = snap['paths'] as Map<String, dynamic>;

  for (final t in targets) {
    final op = (paths[t.path] as Map<String, dynamic>?)?[t.method] as Map<String, dynamic>?;
    if (op == null) {
      stderr.writeln('WARN: missing ${t.method.toUpperCase()} ${t.path}');
      continue;
    }
    final res = _schemaOf(op['responses']?['200']);
    if (res != null) _emitObject(res, t.resName);
    if (t.reqName != null) {
      final req = _schemaOf(op['requestBody']);
      if (req != null) _emitObject(req, t.reqName!);
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_models.dart from the OpenAPI snapshot - do not edit.')
    ..writeln('// Regenerate with tool/gen_models.sh; CI fails if this is stale.')
    ..writeln('//')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln();

  for (final name in _classes.keys.toList()..sort()) {
    _writeClass(out, _classes[name]!);
    out.writeln();
  }

  final dest = File('${_repoRoot()}/apps/mobile-flutter/app/lib/api/models.gen.dart');
  dest.parent.createSync(recursive: true);
  dest.writeAsStringSync(out.toString());
  stdout.writeln('wrote ${_classes.length} models -> lib/api/models.gen.dart');
}

Map<String, dynamic>? _schemaOf(dynamic responseOrBody) {
  if (responseOrBody is! Map) return null;
  return (responseOrBody['content']?['application/json']?['schema']) as Map<String, dynamic>?;
}

/// Model names that would collide with a common Flutter/dart widget or type get
/// a `Data` suffix, so a UI file can import the models and the framework together.
const _reserved = {
  'Row', 'Column', 'Table', 'Image', 'Icon', 'Card', 'Text', 'Divider', 'Center',
  'Padding', 'Stack', 'Align', 'Wrap', 'Flow', 'Chip', 'Badge', 'Banner', 'Hero',
  'Form', 'Scaffold', 'Title', 'Tab', 'Step', 'Page', 'Placeholder', 'Spacer',
  'Notification', 'Action', 'Route', 'Overlay', 'Semantics',
};

/// Register (dedup) an object schema as a class and return its name.
String _emitObject(Map<String, dynamic> schema, String suggested) {
  final sig = _signature(schema);
  final existing = _bySignature[sig];
  if (existing != null) return existing;

  if (_reserved.contains(suggested)) suggested = '${suggested}Data';
  final name = _uniqueName(suggested);
  _bySignature[sig] = name;
  _usedNames.add(name);

  final props = (schema['properties'] as Map<String, dynamic>? ?? {});
  final required = ((schema['required'] as List?) ?? const []).cast<String>().toSet();
  final fields = <Field>[];
  props.forEach((key, raw) {
    final s = raw as Map<String, dynamic>;
    final nullable = (s['nullable'] == true) || !required.contains(key);
    fields.add(_field(key, s, nullable));
  });
  _classes[name] = ModelClass(name, fields);
  return name;
}

bool _isUnion(Map<String, dynamic> s) =>
    s.containsKey('anyOf') || s.containsKey('oneOf') || s.containsKey('allOf');

Field _field(String key, Map<String, dynamic> s, bool nullable) {
  final dartName = _camel(key);
  final q = nullable ? '?' : '';
  final type = _typeOf(s);

  // Union / free-form shapes stay dynamic rather than forcing a lossy class.
  if (_isUnion(s)) {
    return Field(key, dartName, 'dynamic', nullable, _Kind.raw);
  }
  if (type == 'array' && _isUnion(s['items'] as Map<String, dynamic>)) {
    return Field(key, dartName, 'List<dynamic>$q', nullable, _Kind.listScalar,
        elementParse: 'dynamic');
  }

  if (type == 'object') {
    // additionalProperties map or nested class.
    if (s['properties'] == null) {
      final v = s['additionalProperties'];
      final valType = (v is Map<String, dynamic>) ? _scalarDart(v) ?? 'dynamic' : 'dynamic';
      return Field(key, dartName, 'Map<String, $valType>$q', nullable, _Kind.map);
    }
    final cls = _emitObject(s, _pascal(_singular(key)));
    return Field(key, dartName, '$cls$q', nullable, _Kind.object);
  }
  if (type == 'array') {
    final item = s['items'] as Map<String, dynamic>;
    final it = _typeOf(item);
    if (it == 'object') {
      final cls = _emitObject(item, _pascal(_singular(key)));
      return Field(key, dartName, 'List<$cls>$q', nullable, _Kind.listObject, elementParse: cls);
    }
    if (_isDateTime(item)) {
      return Field(key, dartName, 'List<DateTime>$q', nullable, _Kind.listDateTime);
    }
    final sc = _scalarDart(item) ?? 'dynamic';
    return Field(key, dartName, 'List<$sc>$q', nullable, _Kind.listScalar, elementParse: sc);
  }
  if (_isDateTime(s)) {
    return Field(key, dartName, 'DateTime$q', nullable, _Kind.dateTime);
  }
  final sc = _scalarDart(s) ?? 'dynamic';
  final enums = (s['enum'] as List?)?.cast<Object>().map((e) => e.toString()).toList();
  return Field(key, dartName, '$sc$q', nullable, _Kind.scalar, enumValues: enums);
}

void _writeClass(StringBuffer out, ModelClass c) {
  if (c.fields.isEmpty) {
    out.writeln('class ${c.name} {');
    out.writeln('  const ${c.name}();');
    out.writeln('  factory ${c.name}.fromJson(Map<String, dynamic> json) => const ${c.name}();');
    out.writeln('  Map<String, dynamic> toJson() => const {};');
    out.writeln('}');
    return;
  }
  out.writeln('class ${c.name} {');
  for (final f in c.fields) {
    if (f.enumValues != null) {
      out.writeln('  /// One of: ${f.enumValues!.join(', ')}.');
    }
    out.writeln('  final ${f.type} ${f.dartName};');
  }
  out.writeln();
  out.writeln('  const ${c.name}({');
  for (final f in c.fields) {
    out.writeln('    ${f.nullable ? '' : 'required '}this.${f.dartName},');
  }
  out.writeln('  });');
  out.writeln();
  // fromJson
  out.writeln('  factory ${c.name}.fromJson(Map<String, dynamic> json) => ${c.name}(');
  for (final f in c.fields) {
    out.writeln('    ${f.dartName}: ${_parse(f)},');
  }
  out.writeln('  );');
  out.writeln();
  // toJson
  out.writeln('  Map<String, dynamic> toJson() => {');
  for (final f in c.fields) {
    out.writeln("    '${f.jsonKey}': ${_encode(f)},");
  }
  out.writeln('  };');
  out.writeln('}');
}

/// The encode expression for a field, producing a JSON-ready value.
String _encode(Field f) {
  final n = f.dartName;
  final q = f.nullable ? '?' : '';
  switch (f.kind) {
    case _Kind.raw:
    case _Kind.scalar:
    case _Kind.map:
    case _Kind.listScalar:
      return n;
    case _Kind.dateTime:
      return '$n$q.toIso8601String()';
    case _Kind.object:
      return '$n$q.toJson()';
    case _Kind.listDateTime:
      return '$n$q.map((e) => e.toIso8601String()).toList()';
    case _Kind.listObject:
      return '$n$q.map((e) => e.toJson()).toList()';
  }
}

/// The parse expression for a field, reading `json['key']`.
String _parse(Field f) {
  final v = "json['${f.jsonKey}']";
  final n = f.nullable;
  switch (f.kind) {
    case _Kind.raw:
      return v;
    case _Kind.scalar:
      final base = f.type.replaceAll('?', '');
      if (base == 'double') return n ? '($v as num?)?.toDouble()' : '($v as num).toDouble()';
      return n ? '$v as $base?' : '$v as $base';
    case _Kind.dateTime:
      return n ? '$v == null ? null : DateTime.parse($v as String)' : 'DateTime.parse($v as String)';
    case _Kind.object:
      final cls = f.type.replaceAll('?', '');
      return n
          ? '$v == null ? null : $cls.fromJson($v as Map<String, dynamic>)'
          : '$cls.fromJson($v as Map<String, dynamic>)';
    case _Kind.map:
      return n ? '($v as Map<String, dynamic>?)?.cast()' : '($v as Map<String, dynamic>).cast()';
    case _Kind.listScalar:
      final e = f.elementParse == 'double' ? '(e as num).toDouble()' : 'e as ${f.elementParse}';
      final body = '($v as List).map((e) => $e).toList()';
      return n ? '$v == null ? null : $body' : body;
    case _Kind.listDateTime:
      final body = '($v as List).map((e) => DateTime.parse(e as String)).toList()';
      return n ? '$v == null ? null : $body' : body;
    case _Kind.listObject:
      final body =
          '($v as List).map((e) => ${f.elementParse}.fromJson(e as Map<String, dynamic>)).toList()';
      return n ? '$v == null ? null : $body' : body;
  }
}

// --- schema helpers ---

String _typeOf(Map<String, dynamic> s) {
  final t = s['type'];
  if (t is List) return t.firstWhere((e) => e != 'null', orElse: () => 'object') as String;
  return (t as String?) ?? 'object';
}

bool _isDateTime(Map<String, dynamic> s) => s['type'] == 'string' && s['format'] == 'date-time';

String? _scalarDart(Map<String, dynamic> s) {
  switch (_typeOf(s)) {
    case 'string':
      return 'String';
    case 'integer':
      return 'int';
    case 'number':
      return 'double';
    case 'boolean':
      return 'bool';
  }
  return null;
}

/// Structural signature: shape only (keys/types/required), ignoring descriptions,
/// so two identical inline objects share one Dart class.
String _signature(Object? node) {
  if (node is Map) {
    final keep = <String, Object?>{};
    for (final k in node.keys) {
      if (k == 'description' || k == 'example' || k == 'title') continue;
      keep[k as String] = node[k];
    }
    final sorted = keep.keys.toList()..sort();
    return '{${sorted.map((k) => '$k:${_signature(keep[k])}').join(',')}}';
  }
  if (node is List) return '[${node.map(_signature).join(',')}]';
  return jsonEncode(node);
}

String _uniqueName(String base) {
  if (!_usedNames.contains(base)) return base;
  var i = 2;
  while (_usedNames.contains('$base$i')) i++;
  return '$base$i';
}

// --- naming ---

String _camel(String s) {
  final p = _pascal(s);
  return p.isEmpty ? p : p[0].toLowerCase() + p.substring(1);
}

String _pascal(String s) => s
    .split(RegExp(r'[_\-\s]+'))
    .where((w) => w.isNotEmpty)
    .map((w) {
      // Normalise an all-caps token (FIRE) so it camelCases cleanly; leave a
      // token that already carries internal caps (matchId) untouched.
      final base = (w == w.toUpperCase() && w != w.toLowerCase()) ? w.toLowerCase() : w;
      return base[0].toUpperCase() + base.substring(1);
    })
    .join();

String _singular(String s) {
  if (s.endsWith('ies')) return '${s.substring(0, s.length - 3)}y';
  if (RegExp(r'(ch|sh|ss|x|z|s)es$').hasMatch(s)) return s.substring(0, s.length - 2);
  if (s.endsWith('s') && !s.endsWith('ss')) return s.substring(0, s.length - 1);
  return s;
}

String _repoRoot() {
  var dir = Directory.current;
  while (true) {
    if (Directory('${dir.path}/shared/contracts-openapi').existsSync()) return dir.path;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('repo root (shared/contracts-openapi) not found from ${Directory.current.path}');
    }
    dir = parent;
  }
}
